### ISSUE TITLE
Pass-through event handling for some specific layer

### ISSUE THREAD

**Issue by waldenn** [openglobus/openglobus#100]
Is it possible to do pass-through (or pass-on) event handling into a lower layer?

The use case I have for this is showing urbanized regions, but when a user clicks on that polygon geometry, preferably the click would be registered on the country layer (to then show the country info).

The urbanized region object has no country meta-data attached, otherwise that could provide a workaround.

Maybe its possible to only render the urbanization layer, but not have it interact with any click events at all?

**Comment by Zemledelec** [comment]
I've added pickingEnabled layer option(not sure it's a good name for it, I'll be appreciate if you suggest better one), so check it out here: http://openglobus.org/examples/disableLayerPicking/disableLayerPicking.html

**Comment by Zemledelec** [comment]
pickingEnabled is true by default

**Comment by waldenn** [comment]
Works perfectly. Thanks!

The API name sounds good to me. https://en.wiktionary.org/wiki/pickable
