### ISSUE TITLE
events for completing layer rendering

### ISSUE THREAD

**Issue by waldenn** [openglobus/openglobus#102]
Maybe it would be nice to be able to have two new events:

- when a specific layer has finished being rendered:  [layer].events.on("completed", ...
- when ALL visible(?) layers have finished rendering: [globe].planet.on("completed, ...

My use case is for updating and removing the "loading" progress bar upon finishing rendering, as there can be quite some time between loading large amounts of data and the completed rendering.

Another use case would be to hide/show certain user interaction tools, when a certain layer or all layers have been rendered.

**Comment by Zemledelec** [comment]
added planet rendercompleted event and layer loadend event.

Create separate layer rendercompleted will provide in future issues.
