### ISSUE TITLE
configurable transparency blending of base layer tiles

### ISSUE THREAD

**Issue by waldenn** [openglobus/openglobus#103]
See a demo of this concept here: https://www.youtube.com/watch?v=Hu8Yd3-WbP4&t=15m10s

Not sure how feasible this is, but its an interesting concept I think.

**Comment by Zemledelec** [comment]
Isn't it http://openglobus.org/examples/layerOpacity/layerOpacity.html ?

**Comment by waldenn** [comment]
Ah missed that. Nice.
