### ISSUE TITLE
heatmaps

### ISSUE THREAD

**Issue by waldenn** [openglobus/openglobus#111]
An example heatmap [here](http://opengeoscience.github.io/geojs/examples/heatmap/)

Reference implementations:
-   https://github.com/OpenGeoscience/geojs/blob/master/src/heatmapFeature.js
-   https://github.com/pa7/heatmap.js

**Comment by waldenn** [comment]
Maybe the best way for these sorts of non-essential extensions to OpenGlobus would be some sort of (data visualization / UI ) plugin system. Some very useful plugins could then still be included in the core release. Other similar things: legends, arced graphs between points, etc. 

Related: an example of [Deck.gl](http://deck.gl) creating a [3D heatmap](https://github.com/uber/deck.gl/blob/master/examples/website/3d-heatmap/app.js).

**Comment by Zemledelec** [comment]
In this case I use openlayers and leaflet terminology of controls. For example http://openglobus.org/examples/customControl/customControl.html. The basic idea is to create some "control" embeded with engine instance(scene or renderer) e.g. globe.planet.addControl(new MyConrol(myOptions)); I.e. control is an instance that has access to the whole engine.

However the heatmap is more than just ordinary control but (It's like an windmap) like an aggregate of control which provide visualization parameters and layer which represents visual condition. So it could be named as plugin and placed for example in ./plugin folder with control and layer code.

**Comment by Zemledelec** [comment]
As far as I'm concerned, the heatmaps should be made with real 3d volumes and bloom effect around it.

**Comment by jhjojhjo** [comment]
hi.
I tried to draw heatmap using canvastile.
but heatmap point is drawn in every tile because of drawTile function.

I will draw heatmap points  only after all tiles are drawn
[test-heatmap.zip](https://github.com/openglobus/openglobus/files/7859105/test-heatmap.zip)
.
