### ISSUE TITLE
Render sometimes is not full

### ISSUE THREAD

**Issue by Skyline405** [openglobus/openglobus#150]
If you rotate the camera in a certain way, then a part of the grid is not rendered.

Screens:
![og_bug2](https://user-images.githubusercontent.com/8080553/48597052-5970e980-e98e-11e8-9b3c-5b954a4f39aa.png)
![openglobus_bug](https://user-images.githubusercontent.com/8080553/48597054-5970e980-e98e-11e8-84aa-1768f5b7b2d1.png)

This is code result from main page of documentation.

**Comment by Zemledelec** [comment]
Thanks, Skyline405! Im going to fix it as soon as I can.

**Comment by Zemledelec** [comment]
It seems to be working now. 
Not published yet, try it locally.

**Comment by Zemledelec** [comment]
Actually, it needs to be fixed again.

**Comment by Zemledelec** [comment]
It seems to be fixed.
