### ISSUE TITLE
Javascript error (getInternalformatParameter) on openglobus.org

### ISSUE THREAD

**Issue by jeancaffou** [openglobus/openglobus#188]
Happens only on Chrome, example works on Firefox

Example on openglobus.org fails to load (black screen) with the error:
```
Uncaught TypeError: e.getInternalformatParameter is not a function
    at Ss.getMaxMSAA (og.js?16:21)
    at new Ss (og.js?16:21)
    at new Us (og.js?16:21)
    at start (start.js?3:10)
    at onload ((index):45)
```

**Comment by Zemledelec** [comment]
Seems to be that your browser doesn't support webg2. I fixed msaa cheking in webgl1 mode. Check it up! I strongly recommend you to clear the cache like this: 
![image](https://user-images.githubusercontent.com/5452251/63222245-ed861080-c1ad-11e9-8be5-10ab5f5fed8b.png)

Havent made exaples publishing yet((

**Comment by jeancaffou** [comment]
Clearing cache works. Thanks
