### ISSUE TITLE
Initializing camera

### ISSUE THREAD

**Issue by Wiljanneman** [openglobus/openglobus#227]
Hi

Am I correct in assuming one would need to use the camera module to set a default camera angle?  Is there an example somewhere explaining the basic usage?

Thanks in advance

**Comment by Zemledelec** [comment]
Hi! Haven't made yet a good example. If you have any ideas or wishes what could it be for example case I'll do my best! Now, you can check only the code inside examples modules in the /camera folder and here http://openglobus.org/examples/customScene/customScene.html where I show that you can us even your own camera matrices, and here http://openglobus.org/examples/customControl/customControl.html?e=908149.62233,4860797.20563,5313757.22617&f=-0.15840,-0.09619,-0.98268&u=-0.00367,0.99529,-0.09683 where you can find camera setters and update functions.

**Comment by Wiljanneman** [comment]
Thanks!  Works like a charm

**Comment by Zemledelec** [comment]
Replace to https://github.com/openglobus/openglobus/issues/246
