### ISSUE TITLE
Accented text in label

### ISSUE THREAD

**Issue by screwt** [openglobus/openglobus#239]
The below text doesn't appear on the map
```
 .add(new og.Entity({
            lonlat: [
                **,
                **,
            ],
            label: {
                text: "Vous êtes ici.",
                outline: 0.77,
                outlineColor: "rgba(255,255,255,.4)",
                size: 27,
                color: "black",
                face: "Lucida Console",
                offset: [-50, 100]
            }
        }))
```

![screenshot](https://user-images.githubusercontent.com/2142989/77244527-eaf10b00-6c15-11ea-954f-d92bfdc8a2a3.png)

**Comment by Zemledelec** [comment]
Strange. Ive tried from chrome conosle to set it manually someLayer._entities[0].label.setText("Vous êtes ici"); It looks fine.

![image](https://user-images.githubusercontent.com/5452251/77245759-0a962c80-6c32-11ea-9e78-8847e3636182.png)

Could you check script file encoding with UTF8 and find character ê in src/og/utils/fontAtlas.js ?

**Comment by Zemledelec** [comment]
Try to set js script file, with label text, encoding to UT8(without signature) codepage 65001.

**Comment by screwt** [comment]
You were right i was encoding my file in latin-**** editor miss configuration.
Thank you.
