### ISSUE TITLE
Support for 512 x 512 tiles

### ISSUE THREAD

**Issue by maule64** [openglobus/openglobus#244]
Please add support for XYZ tiles of different image sizes: some TMS, such as NASA GIB tile server, return 512x512 tiles.

**Comment by Zemledelec** [comment]
Could you give me an example of such image tile provider? ...As far as I know it's possible, but I'm not sure.

**Comment by Zemledelec** [comment]
![image](https://user-images.githubusercontent.com/5452251/78505830-b38a6e80-777e-11ea-88aa-3342f1cd538d.png)
Like this?

**Comment by maule64** [comment]
Da: Info e-Soft [mailto:info@e-soft.it] 
Inviato: lunedì 6 aprile 2020 09:37
A: 'openglobus/openglobus'
Oggetto: R: [openglobus/openglobus] Support for 512 x 512 tiles (#244)

 

Hi,

 

this is an example:

 

https://gibs-a.earthdata.nasa.gov/wmts/epsg4326/best/MODIS_Terra_CorrectedReflectance_TrueColor/default/2020-04-04/EPSG4326_250m/3/2/4.jpg

 

The api is described at this link: https://wiki.earthdata.nasa.gov/display/GIBS/GIBS+API+for+Developers

 

This tile server is very interesting because shows historical meteo data from satellites.

 

Best,

Mauro

 

Da: Michael Gevlich [mailto:notifications@github.com] 
Inviato: domenica 5 aprile 2020 19:49
A: openglobus/openglobus
Cc: maule64; Author
Oggetto: Re: [openglobus/openglobus] Support for 512 x 512 tiles (#244)

 

 <https://user-images.githubusercontent.com/5452251/78505830-b38a6e80-777e-11ea-88aa-3342f1cd538d.png> image
Like this?

**Comment by Zemledelec** [comment]
![image](https://user-images.githubusercontent.com/5452251/78536908-3bac5a80-77f7-11ea-99e5-3123c671ac53.png)

Try this:
```
let modis = new XYZ("modis", {
    'isBaseLayer': true,
    'url': "//gibs-a.earthdata.nasa.gov/wmts/epsg3857/best/MODIS_Terra_CorrectedReflectance_TrueColor/default/2020-04-04/EPSG3857_250m/{z}/{y}/{x}.jpg",
    'visibility': true,
    'maxNativeZoom': 9 // >=10(~250m) no tiles I see
});
```
**Little description**
Unfortunately globus cannot render 4326(or any other) projection on the globe, it's always 3857(900913) and right now the only way is to use 3857 tileset, wms etc. In the url above there is 4326 I've changed to 3857, and it works fine for me.
4326:
https://gibs-a.earthdata.nasa.gov/wmts/epsg4326/best/MODIS_Terra_CorrectedReflectance_TrueColor/default/2020-04-04/EPSG4326_250m/0/0/0.jpg
3857:
https://gibs-a.earthdata.nasa.gov/wmts/epsg3857/best/MODIS_Terra_CorrectedReflectance_TrueColor/default/2020-04-04/EPSG3857_250m/0/0/0.jpg

P.S.
for example, If it's dark try to play with:
globe.planet.renderer.gamma = 0.7;
globe.planet.renderer.exposure = 3;

and layer options:
    'specular': [0.0003, 0.00012, 0.00001],
    'shininess': 20,
    'diffuse': [0.89, 0.9, 0.83],

**Comment by Zemledelec** [comment]
In https://wiki.earthdata.nasa.gov/display/GIBS/GIBS+API+for+Developers#GIBSAPIforDevelopers-WGS84/Lat-lon/Geographic(EPSG:4326)

There is good **Projections & Resolution** section. 3857 is the only projection globe work with.
On the poles >85 <-85deg. globe show  WMS on 4326 only.

**Comment by maule64** [comment]
It works very fine!

NASA GIBS also support multi-server parameter "{s}":

https://gibs-{s}.earthdata.nasa.gov/wmts/epsg3857/best/MODIS_Terra_CorrectedReflectance_TrueColor/default/2020-04-04/EPSG3857_250m/{z}/{y}/{x}.jpg

P.S.: We work with GIS Systems and I asked to contact you on linkedin as "Mauro"...

**Comment by Zemledelec** [comment]
Good!
