### ISSUE TITLE
Make camera and planetCamera examples

### ISSUE THREAD

**Issue by Zemledelec** [openglobus/openglobus#246]

**Comment by alacst** [comment]
Hey Mike,
can you make an example on these? I'm trying to use the flyLonLat function with the camera ending up looking at the scene at a certain angle. All I've found is the billboards on the ground example, where you set the camera with 3 vectors (eye, look, up). Unfortunately I cannot figure out how to set these vectors for my need.
Thank you!

**Comment by Zemledelec** [comment]
Check this out!
http://openglobus.org/examples/cameraFly/cameraFly.html

P.S.
Not the best looking view trajectory, I suppose this is another task:)
