### ISSUE TITLE
Marker beeing rendered when it should not.

### ISSUE THREAD

**Issue by screwt** [openglobus/openglobus#251]
On the page https://www.openglobus.org/ you can reproduce this bug.

Here is a video:

![output](https://user-images.githubusercontent.com/2142989/79354547-d49c4d80-7f3c-11ea-9c2f-8db98cfb15a6.gif)

**Comment by Zemledelec** [comment]
Actually, interesting question. There is an option for Vector layer polygonOffsetUnits which is **The multiplier by which an implementation-specific value is multiplied with to create a constant depth offset** is -637000.0 by default. You can vary this option to get appropriate exposition among the hills. For example polygonOffsetUnits resolve the issue, but part of the label goes under the ground:
```
new Vector("Markers", {
    clampToGround: true,
    polygonOffsetUnits: 0
})
    .addTo(globe.planet)
    .add(new Entity({
        lonlat: [5.73, 45.183],
        label: {
            text: "Hi, Globus!",
            outline: 0.77,
            outlineColor: "rgba(255,255,255,.4)",
            size: 27,
            color: "black",
            face: "Lucida Console",
            offset: [10, -2]
        },
        billboard: {
            src: "./marker.png",
            width: 64,
            height: 64,
            offset: [0, 32]
        }
    }));
```
another option for z buffer sorting is polygonOffsetFactor(0 by default) which is **The scale factor for the variable depth offset.**

Here is a description https://www.khronos.org/registry/OpenGL-Refpages/es2.0/xhtml/glPolygonOffset.xml

Maybe the best way is to make labels z-offset depends on altitude or distance - the ways I prefer in real cases. For example on low altitude I set polygonOffsetUnits to zero, on high altitude I enlarge the parameter.

So, there is an option which makes visualization appropriate, but right now there is no option to make it automatically. I'll think about it...

Always glad to hear any suggestion

Cheers!

**Comment by screwt** [comment]
Understood. 
-637000 is a webgl default or openglobus default?

**Comment by Zemledelec** [comment]
Openglobus default. 0 for gl.

**Comment by Zemledelec** [comment]
I use cheap planet triggers like this:
```
globe.planet.events.on("draw", () => {
    myVectorLayer.polygonOffsetUnits = getOffestByCameraPosition(globe.planet.camera)
});
```
planet camera has a lot of parameters such as slope, altitude, front vectors etc.

**Comment by screwt** [comment]
This issue can be closed if you want i think
