### ISSUE TITLE
 MapboxTerrain with XYZ osm layer anomaly

### ISSUE THREAD

**Issue by karpatidaniel** [openglobus/openglobus#263]
Dear All!

I have encountered an issue when using OSM layer with MapBox terrain.

The symptoms are:

- quite often, when zoomed and tilting the camera the neighboring tiles are displayed incorrectly 

I have attached a short video of this behavior (sorry for low quality), but below is a screenshot respresenting this display-anomaly.

![thames_weird](https://user-images.githubusercontent.com/25864223/87578359-9990ee00-c6d4-11ea-8cd5-198913509a96.png)

I've cloned the repo and tested it with the Globus Terrain and that seems fine with osm layer, however we are planning to use MapboxTerrain + osm layer.
Our goal is to display our lake bed elevation data at high resolution (0.1 meters). Our data is converted with gdal2tiles (down to zoom level 25) and we host it locally. The demonstration screenshot (above) and video is taken from mapbox server using directly the OpenGlobus mapbox terrain example from your site. At lower zoomlevel we did not notice any issue. I have also cleared my web cache, but no success.
For information, the two errors on the screenshot occured much earlier, maybe wen I was navigating from the initial example position (Im not sure if they are the root of this problem.):
informational errors in my chrome console: 

- http://api.mapbox.com/v4/mapbox.terrain-rgb/6/31/20.pngraw?access_token=pk.eyJ1IjoiZm94bXVsZGVyODMiLCJhIjoiY2pqYmR3dG5oM2Z1bzNrczJqYm5pODhuNSJ9.Y4DRmEPhb-XSlCR9CAXACQ

- http://api.mapbox.com/v4/mapbox.terrain-rgb/6/31/20.pngraw?access_token=pk.eyJ1IjoiZm94bXVsZGVyODMiLCJhIjoiY2pqYmR3dG5oM2Z1bzNrczJqYm5pODhuNSJ9.Y4DRmEPhb-XSlCR9CAXACQ

![Desktop 2020 07 15 - 19 14 09 03_cut](https://user-images.githubusercontent.com/25864223/87579037-9cd8a980-c6d5-11ea-827a-259bf30c03d9.gif)

Any help is appreciated.
Best regards: Daniel Karpati

**Comment by Zemledelec** [comment]
Hi Daniel!

I've caught the bug. It also affects bil terrain data. I have fixed it locally just now! Give me a time to release it...

**Comment by Zemledelec** [comment]
Fixed with https://github.com/openglobus/openglobus/releases/tag/v0.4.3
