### ISSUE TITLE
issue with lighting off

### ISSUE THREAD

**Issue by alacst** [openglobus/openglobus#265]
Hey,

I've noticed some rendering issues with the lighting turned off when tilting the camera. Seems like it affects the example code aswell.

With the lighting on, everything is fine:
![kép](https://user-images.githubusercontent.com/22245820/87774258-973da980-c824-11ea-979b-e3719b81e703.png)

But when turned off, random blue shapes appearing:
![kép](https://user-images.githubusercontent.com/22245820/87774486-e1268f80-c824-11ea-8c8b-d648457b7799.png)

The console reports no errors, I've tried several browsers, same results. I wasn't able to locate the origin of this in the code.

Any ideas? Thank you!
Tibor

**Comment by Zemledelec** [comment]
Hi Tibor! Good bug, I almost forget that globe has no lighting pass)) I've got the problem. I'll try to fix it with next release.

**Comment by Zemledelec** [comment]
Fixed with https://github.com/openglobus/openglobus/releases/tag/v0.4.3
