### ISSUE TITLE
rendering negative terrain data

### ISSUE THREAD

**Issue by alacst** [openglobus/openglobus#266]
Hey,

I've been playing around with the Mapbox terrain. With a custom tileset using heights ranging from -50 to -300 meters, the library seem to ignore values lower than -100m and render a much higher constant surface. According to the Mapbox RGB terrain tile coding, the range should be starting around -3400m.
Tried to debug without success, any help would be greatly appreciated.

Thanks,
Tibor

**Comment by Zemledelec** [comment]
TerrainWorker.js 232 etc. Ill fix it, need somehow to solve no data points which are always big negative and the same time compativle with differend terrain data sources.

**Comment by alacst** [comment]
I'll check it, thank you!
