### ISSUE TITLE
API

### ISSUE THREAD

**Issue by fridl8** [openglobus/openglobus#267]
The API documentation page on the website has been showing a 404 for myself and a few others I've talked to for the past week or so.  I didn't see any contact information on the site or GitHub page for an issue like this and I wanted it to get some visibility.  Is there another place to check the documentation?

**Comment by Zemledelec** [comment]
Thank you! I missed it when removed to another host server. I'll fix it!

**Comment by Zemledelec** [comment]
Done! [API](https://www.openglobus.org/api/). Have to say, the API is not full and sometimes out of date. I suggest to look at the [examples](https://www.openglobus.org/examples.html) first.
