### ISSUE TITLE
Question about gridSizeByZoom in Terrain classes

### ISSUE THREAD

**Issue by karpatidaniel** [openglobus/openglobus#271]
Hi 

I have a question related to the gridSizeByZoom array in the GlobusTerrain class. 
Actually I am using it in MapboxTerrain, but I need a little more precise terrain around zoom level 21. How should I modify the gridSizeByZoom array to achieve this?

I have tried to use this one:
`this.gridSizeByZoom = [64, 32, 32, 16, 16, 16, 16, 16, 64, 32, 32, 16, 16, 16, 32, 64, 128, 128, 128, 128, 128, 128];`
This code produces blue grids when the page is laoding, and also sometimes when I am just zooming in and out between some specific zoom levels, sometimes they start fulfilling my screen after some seconds when camera is fixed.

My minZoom is 10 and maxZoom is 21. The tiles data I think is correct.

By changing the gridSizeByZoom array I sometimes got 
'Uncaught TypeError: Cannot read property 'NaN' of undefined' at Segment.prototype._getIndexBuffer function.

The default gridSizeByZoom array in the globusTerrain class produces sharp edges and pyramid figures when zoomed to 21 (or either it masks the terrain data), this is why I want to increase the resolution.

default gridSizeByZoom:
![closeup terrain lvl21 default](https://user-images.githubusercontent.com/25864223/91058164-6f621280-e628-11ea-96f4-b35c895f017a.png)

modified to `[64, 32, 32, 16, 16, 16, 16, 16, 64, 32, 32, 16, 16, 16, 32, 64, 128, 128, 128, 128, 128, 128];`
It's almost the precision I am trying to reach.
![closeup terrain lvl21 precise](https://user-images.githubusercontent.com/25864223/91058220-7db02e80-e628-11ea-843a-7e0856b9c847.png)

This is what the blue grids look like:
![bluegrid2](https://user-images.githubusercontent.com/25864223/91056243-05e10480-e626-11ea-92fd-e28e37d8e8d2.png)
![bluegrid3](https://user-images.githubusercontent.com/25864223/91056264-0d081280-e626-11ea-84c4-7df6434a81e2.png)
They continuously appearing until they fulfill the screen completely.

Any suggestion?

**Comment by Zemledelec** [comment]
Hi, karpatidaniel!

Are you sure that mapbox terrain has 21 zoom level precision?

I have tried 20 level and see "squared" elevation image:

![image](https://user-images.githubusercontent.com/5452251/91063889-341b1000-e637-11ea-8050-a72f64b63209.png)


As far as I understand current mapbox terrain realization has already enough precision maxZoom is 15. If I wrong I ll try to fix it! 

Could you give me an terrain example image of 21 level?

**Comment by Zemledelec** [comment]
For the previaous answer I have this for 21 zoom level:

![image](https://user-images.githubusercontent.com/5452251/91068251-ae9a5e80-e63c-11ea-96d8-183ae1748f58.png)

P.S.
And yes there is a bug for 128 grid size. 64 only works fine. I'll make a fix.

**Comment by karpatidaniel** [comment]
Thank you Zemledelec.
If you need my elevation tiles I can send it (only 1MB zipped for this tiny area).

**Comment by Zemledelec** [comment]
Could you send me your tile set to my email mgevlich@gmail.com, please?

**Comment by Zemledelec** [comment]
![image](https://user-images.githubusercontent.com/5452251/91345063-7daa5d00-e7e7-11ea-9d80-c690fafd81ee.png)
![image](https://user-images.githubusercontent.com/5452251/91345080-8438d480-e7e7-11ea-904c-fa0855b0fc42.png)
![image](https://user-images.githubusercontent.com/5452251/91345134-96b30e00-e7e7-11ea-9d57-bdedd4ff55f8.png)
![image](https://user-images.githubusercontent.com/5452251/91345220-b0ecec00-e7e7-11ea-9f3a-14c9ab560054.png)



Does it look good? A lot of artifacts around...nodata or may be another bug?)

**Comment by karpatidaniel** [comment]
The tileset I sent you contains nodata. With a correct tileset it looks great. We are still testing it.
Thank you.

**Comment by alacst** [comment]
Hey,

It's way better than before. However, with the correct tileset, max zoom set to 21 and 64 being the max value in the gridsizebyzoom array, some blue tearing appears.
![kép](https://user-images.githubusercontent.com/22245820/91434802-a5d8a100-e865-11ea-95fd-8799848be761.png)

Still testing though.

Thank you

**Comment by Zemledelec** [comment]
Did you fill manually gridSizeByZoom like [64, 32, 32, 16, 16, 16, 16, 32, 64, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 64, 32, 16... ... ... ...] up to 64 + 4(for example),

```
window.globe = new Globe({
    'name': "Earth",
    'target': "earth",
    'terrain': new MapboxTerrain(null, {
        url: "./tiles_nonscaled_orig_near/{z}/{x}/{y}.png",
        minZoom: 9,
        maxZoom: 64,
        gridSizeByZoom: [64, 32, 32, 16, 16, 16, 16, 32, 64, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, ... ... ... etc 64, 32, 16],
    }),
    'layers': [...]
});
```

**Comment by alacst** [comment]
Yes, we've been playing around with the array.
The attached pic used that array:
`this.gridSizeByZoom = [8, 8, 8, 16, 16, 16, 32, 32, 32, 32, 32, 32, 32, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64];`
Memory load is pretty high with 64 or 128 at the higher zoom levels, the details are looking good.
If I'm not mistaken, that array goes from 0...1...2... zoom levels telling the renderer to use the given number of verticles. Is there any rule we need to follow when filling the array?

Thank you.
PS. I can mail you our hosted prototype if you're interested

**Comment by Zemledelec** [comment]
Yes, could I take a glance to the prototype? mgevlich@gmail.com

**Comment by alacst** [comment]
Hey,
It should be there.
Thank you
