### ISSUE TITLE
Visible terrain tile borders and blue tearing

### ISSUE THREAD

**Issue by alacst** [openglobus/openglobus#279]
Hey Mike,

I've noticed 2 possible bugs in the library.
The tile borders are visible on all terrain providers. I'm almost certain this came within the last few versions.
The other one comes with camera movement. Some angles make a blue layer growing slowly.
Here's a pic of them both:
![kép](https://user-images.githubusercontent.com/22245820/99679759-98097500-2a7c-11eb-8205-91e3a8e38a92.png)
Thats the layer height example from the site.

Cheers!

**Comment by Zemledelec** [comment]
Hi, Alacst!

> The tile borders are visible on all terrain providers.

Unfortunately, the bug has always been. It's less visible on a satellite layer. I can't fix it right now.

> The other one comes with camera movement. Some angles make a blue layer growing slowly.

I'll try to fix the bug in the next release.

**Comment by Zemledelec** [comment]
http://openglobus.org/examples/customControl/customControl.html?e=3925092.00286,3581456.33304,-3540876.96315&f=0.06108,-0.58323,0.81001&u=0.97905,0.19293,0.06509
