### ISSUE TITLE
Can it draw circles?

### ISSUE THREAD

**Issue by alacst** [openglobus/openglobus#281]
Hey,

Is it possible to draw circles? Like a distance measurement around a point.
Leaflet draw can output JSON circle features with a given point and radius. I've tried to use this as a vector layer, but it seems like the API doesn't support circles.

Thank you

**Comment by Zemledelec** [comment]
Hi, alacst! You can use Polygon from geoJson. But right now you should make coordinates of a circle by yourself. I prefer to use Polyline and Vector layer groundRelative option, like here: https://openglobus.org/examples/polylineOnTheGround/polylineOnTheGround.html.
But circle coordinates it is up to you. I could make it as api part, but don know how to make it properly. 
Any suggestions?

Cheers!

**Comment by alacst** [comment]
Hey, I was thinking maybe using the billboards for this. With a custom png/svg and a fixed size property that won't let the engine scale it to the screen but scale it to the current scaling to be sized correctly all the time.

**Comment by Zemledelec** [comment]
1) Don't like it. I mean how to make circles for instance: 
```
new Entity({
  polyline: {
      pathLonLat: createCirleCoordinates(centerLonLat, radius);
  }
})?
```
2) Do you need solid circle or just outline?

**Comment by alacst** [comment]
I've tried using the polyline. Drawing just a circle already seems to be harder than I tought.
![kép](https://user-images.githubusercontent.com/22245820/102500608-c9c22b80-407c-11eb-89b3-6a820de2a024.png)
I'm getting an ellipsis instead of a circle. The problem is that I'm calculating the points from the center LonLat, so my radius will be distored depending on the location. At 0,0 lonlat, it's a perfect circle. I'm trying to calculate a distance between the center point and the most northern and eastern points, to correct the radius during the drawing. Your distance calculating algorithm seems to return bad values at certain angles around the point. Tried another implementation, no luck.

My goal would be to show distance from a marker with concentric circles around it, like this:
![kép](https://user-images.githubusercontent.com/22245820/102501438-bc597100-407d-11eb-9bbb-c7f9494220e2.png)
So I need just the outline. Also I will have to figure out how to write the distances on each circle.

Cheers!

**Comment by alacst** [comment]
Not related to this question but I have run into some problems with webgl. On iOS, webGL 2.0 is disabled by default. Running the lib like this is super fast but I can see some differences in the appearance of the terrain. If I enable 2.0, I'm getting a null object from the getMaxMSAA function in Renderer.js (line 532), therefore it won't even load. Running on anything else but iOS is fine (a bit slow, maybe my older hw), I don't really understand this yet.

**Comment by Zemledelec** [comment]
Making an example:
![image](https://user-images.githubusercontent.com/5452251/102641550-4df3dc00-416d-11eb-83e7-a1d574be7ddc.png)

**Comment by Zemledelec** [comment]
> Not related to this question but I have run into some problems with webgl. On iOS, webGL 2.0 is disabled by default. Running the lib like this is super fast but I can see some differences in the appearance of the terrain. If I enable 2.0, I'm getting a null object from the getMaxMSAA function in Renderer.js (line 532), therefore it won't even load. Running on anything else but iOS is fine (a bit slow, maybe my older hw), I don't really understand this yet.

I'll check it up.

**Comment by Zemledelec** [comment]
Here is the example http://openglobus.org/examples/circlesOnTheGround/circlesOnTheGround.html

**Comment by alacst** [comment]
Looking great! Thank you
