### ISSUE TITLE
Add Release Build Examples

### ISSUE THREAD

**Issue by Flemingjp** [openglobus/openglobus#283]
All examples import from source, not from any release build. It would be good to see examples using the release builds, as I am unable to import the correct classes uses the release build.

**Comment by Zemledelec** [comment]
Like this https://github.com/openglobus/openglobus/tree/master/examples ?

Sorry, I don't understand, could you please provide specific example?

**Comment by Flemingjp** [comment]
```js
import { Globe } from '../../src/og/Globe.js';
import { GlobusTerrain } from '../../src/og/terrain/GlobusTerrain.js';
import { XYZ } from '../../src/og/layer/XYZ.js';
```
 But using the `og-0.5.8.js` release build instead. I am currently unable to import those classes - I maybe missing something but an example would be appreciated.

**Comment by Zemledelec** [comment]
Actually, I've never thought about this. For now I'd recomend use the whole repo as I do. But I'll see what I can do. I have found this https://medium.com/@adostes/authoring-a-javascript-library-that-works-everywhere-using-rollup-f1b4b527b2a9. Could help I think.
P.S.
Also, you are welcome to improve it! ;)

**Comment by pavletto** [comment]
@Flemingjp we create [@openglobus/og](https://www.npmjs.com/package/@openglobus/og) npm package - you can try using it and import  openglobus like npm dependency!
