### ISSUE TITLE
Incorrect vector tile rendering on high zoom levels

### ISSUE THREAD

**Issue by Zemledelec** [openglobus/openglobus#285]

**Comment by jdohm** [comment]
Not sure if this is the same, but there seems to be a bug with chromium on Ubuntu which renders some things incorrect (even though they are rendered correctly on Firefox or any browser I tested on Windows/Android)

Here is an example of this happening inside the brave browser on Ubuntu. The missing part of the yellow polyline is another polyline behind the globe. 

![image](https://user-images.githubusercontent.com/9203094/110166591-e278ec80-7df4-11eb-8913-c038917bd6d6.png)

The page where this happens is up and running on [OpenIdea.io](https://openidea.io/?Idea=108)

**Comment by Zemledelec** [comment]
First quick, If you use layer Vector try option `'polygonOffsetUnits': -100000`(more or less), for example. 
```
let layer = new Vector(`rayLayer`, {
            ....
            'entities': [],
            'polygonOffsetUnits': -100000,
        });
```

**Comment by jdohm** [comment]
I'm using the vector layer, but I'm not using rays, what you see are polylines (just in case this matters). 

Setting `polgygonOffsetUnits` to `-100000` doesn't have any effect (at least that I can tell). As this issue only arises when using a chromium based browser on linux, this isn't that critical to fix for me right now. 

Just for clarification what I'm doing: 
```
         pointLayer.add(new IdeaEntity({
             'name': id,
             'polyline': {
                 'pathLonLat': [ideaCoords],
                 'thickness': 20,
                 'color': "rgb(255-votes*5,255,0)"
             }
         }));

        let pointLayer = new Vector("points", {
            'async': false,
            'polygonOffsetUnits': -100000
        });
```

**Comment by jdohm** [comment]
Hey @Zemledelec just wanted to let you know, your new font example has the same problem as I have described [3 comments up](https://github.com/openglobus/openglobus/issues/285#issuecomment-791646793)

The white text gets rendered above the black one. 
![image](https://user-images.githubusercontent.com/9203094/111891944-165c3080-89f7-11eb-852d-8ab620608fab.png)

This only happens on chromium based browsers used with Ubuntu (could be a chromium bug).

**Comment by Zemledelec** [comment]
Hi, jdohm! Could you please check it up again? I've made a few fixes.

Explanation:
polygonOffsetUnits: -100000 too large for 16 bit ubuntu z buffer. I changed the value to 0.

**Comment by jdohm** [comment]
Hi @Zemledelec, you got a tiny PR (correcting the include path from Entity to entity) but other than this, you fixed both of my issues (https://github.com/openglobus/openglobus/issues/285#issuecomment-791646793 and https://github.com/openglobus/openglobus/issues/285#issuecomment-803502260). Great work!

**Comment by Zemledelec** [comment]
Closed for https://github.com/openglobus/openglobus/issues/305
