### ISSUE TITLE
getLonLatFromPixelTerrain sometimes returns wrong height 

### ISSUE THREAD

**Issue by jdohm** [openglobus/openglobus#295]
This is for example a problem on the [billboardsDragging example](http://openglobus.org/examples/billboardsDragging/billboardsDragging.html) where you can't reliable created billboards on the pole region. 

If you add `ll.height = 0;` before setting the billboard it works just fine (besides that depending on where you click, you click right through the billboard and create a new billboard instead of moving the selected one - this could mean that the problem isn't actually inside the getLonLatFromPixelTerrain function itself).

I'll see if I myself find why this is happening but for now I simply set height to 0 before setting a billboard.

**Comment by Zemledelec** [comment]
Hmm, interesting! Thanks! I'll check it up.

P.S.
Yep, poles and billboard highly likely are broken somehow...

**Comment by jdohm** [comment]
This isn't specific to billboards nor poles for what I can tell. 
It's only more likely to happen on the poles for some reason but this also happens with polylines and on other places (just not as often).
