### ISSUE TITLE
Vector geometry misaligned lines

### ISSUE THREAD

**Issue by karpatidaniel** [openglobus/openglobus#305]
Hi,
We are experiencing the following output when using geoJSON-based geometry on vector layer. Our geoJSON stands of basically elevation contour points, each feature represents 1m elevation contour.
![image_2021_04_19T13_26_47_440Z](https://user-images.githubusercontent.com/25864223/115252120-785da200-a12b-11eb-882d-7cb62fdcbc69.png)
![image_2021_04_19T13_26_56_837Z](https://user-images.githubusercontent.com/25864223/115252129-7b589280-a12b-11eb-80d4-c1e05a7a2b72.png)

Displaying the input on geojson.io website, we are seeing a more precise polygon. Zoom scale is much lower than what we used on Globus.

![image_2021_04_19T13_26_08_536Z](https://user-images.githubusercontent.com/25864223/115251979-59f7a680-a12b-11eb-8437-322ed220b5b1.png)

At first we tried polylines as contours, but we faced performace issues with over 20k contour points (divided between 550 features), however they are displayed correctly. We used it similarly to the ground-clamped circles.

Is this a bug? Can you suggest a method by which we can display elevation contours with 20-40k points totally and a few hundreds of features?

Here is an example of geometry.
[http://alacst.ddns.net:8181/openglobus.html?JSON=thames#1](http://alacst.ddns.net:8181/openglobus.html?JSON=thames#1)

And here is the geoJSON we used
[https://drive.google.com/file/d/1r5uiJWHf8s4qvWgnHV7W170-hOOHtrTn/view?usp=sharing](https://drive.google.com/file/d/1r5uiJWHf8s4qvWgnHV7W170-hOOHtrTn/view?usp=sharing)

**Comment by Zemledelec** [comment]
Hi! I know the source of the bug. I'll fix it as soon as possible. Sorry, but need time.

P.S. Clamping to the ground means that each point of the ground clamped geometry is checked for collision with terrain. So, you have performance issue. Better use vector geojson as you do, or turn off ground clamping, but you need each point height above ellipsoid in geojson...actually, I cant say it is also works, but sounds good!:) Have to check it too.

**Comment by Zemledelec** [comment]
Hey! (master updated)

maxZoom property doesn't work in this case! But you can try decrease terrain option new EmptyTerrain({
        gridSizeByZoom: [32, 16, 16, 8, 4, 4, 4, 4, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]
    })
for only 21 zoom levels, for now, it doesn't solve the problem, and I'm working on it, but it is the only way for now. Of course  it will not help if you show more than 21 zoom level terrain.

To be continue...

**Comment by Zemledelec** [comment]
...another tip! You could try geoserver for your geojson rasterization(publication) and use WMS layer for it! 

http://openglobus.org:8080/geoserver/tiger/wms?service=WMS&version=1.1.0&request=GetMap&layers=tiger%3Apoly_landmarks&bbox=-74.047185%2C40.679648%2C-73.90782%2C40.882078&width=528&height=768&srs=EPSG%3A4326&format=application/openlayers


http://openglobus.org/examples/layerSwitcher/layerSwitcher.html look USA population in the Layer Switcher

**Comment by Zemledelec** [comment]
I've fixed lines! You could please check it out in the https://github.com/openglobus/openglobus/tree/bugfix/305_geojson_misaligned

**Comment by karpatidaniel** [comment]
Much better, thank you.
![image](https://user-images.githubusercontent.com/25864223/115897294-8cbbda80-a45c-11eb-9ec6-9d9aaade1325.png)

We are considering the use of geoserver. It seems a quite good opportunity.

**Comment by Zemledelec** [comment]
Closed wia https://github.com/openglobus/openglobus/pull/309
