### ISSUE TITLE
Methods to clean up the globe

### ISSUE THREAD

**Issue by wizzed** [openglobus/openglobus#310]
I have an issue where 4 dedicated workers are created every time a map is created. Are there any methods to clear up the workers or to clean up the map?

**Comment by Zemledelec** [comment]
As far as I understand there is no such method. Could you check the setTerrain function here: https://github.com/openglobus/openglobus/blob/680cd76b89b9f6f8483ad3b169a722fce0b286f1/src/og/scene/Planet.js#L557
does it suit you?

...and maybe somehow extract part of the code in a method? If not, could you please be more specific what you want to do?

P.S.
It'is based on http://openglobus.org/examples/terrainSwitch/terrainSwitch.html example.

**Comment by wizzed** [comment]
I would like to clear all references and clear all memory usage, some sort of globe.clearAll(), or globe.delete()  which clears everything and free up the memory.

**Comment by Zemledelec** [comment]
Also, do you want to stop animation, handlers etc. and remove webgl context completely?

**Comment by wizzed** [comment]
Yes, everything, I'm using reactjs and it kinda eats up memory everytime I navigate back and from the map page. So I'm kinda looking for a way to clean up the map efficiently...

Unless I'm using it wrongly?

**Comment by Zemledelec** [comment]
Ok! Got it! Need time.

P.S.
Think it's not easy. Can't relay on the gc only.

**Comment by Zemledelec** [comment]
Replaced to https://github.com/openglobus/openglobus/issues/691
