### ISSUE TITLE
How to create webgl custome layer?

### ISSUE THREAD

**Issue by FreeGIS** [openglobus/openglobus#311]
As everyone knows,mapboxgl,cesium and arcgis api both support webgl custom layers,can you tell me how to create custome layer with openglobus?

**Comment by Zemledelec** [comment]
There are three ways:

1) There is an example http://openglobus.org/examples/geoTexture2d/geoTexture2d.html. It demonstrates how to show webgl framebufer in the surface. 

2) Here is http://openglobus.org/examples/canvasTiles/canvasTiles.html which shows how to use Mercator Grid for custom images

3) API allows redraw each tile based on the tile image with some palette for instance, but there is no example...now.

**Comment by wewindy** [comment]
Hope can support custom webgl layer like mapbox gl's.

**Comment by Zemledelec** [comment]
Doesn't the examples above looks like custom webgl layers?

**Comment by wewindy** [comment]
The examples above are pretty nice! 
Thanks for your contribution. @Zemledelec 

mapboxgl support a custom layer api that provides two simple params, when on layer add to `map`, `gl` & `mapbox map` params can get in the callback function. And for every frame, the mvp matrix and `gl` can get in the `render` callback function. 
So we can use this params to create some funny layer.

`OpenGlobus` is more flexible, its api are more "gis and webgl friendly", I wish this lib can maintain friendly api but also can support some low-level api so developers can have the ability to access webgl, to make more imaginative demos.

**Comment by Zemledelec** [comment]
Thank you! Good point! 

I have an experience in leaflet, and openlayers, and try to support something similar in openglobus. Also make native webgl context as much accessible as possible, so it is very handy.

As far as I understand you want a convenient way to render map tiles.  **In terms of supporting custom layers, could you you be more specific what you want to see? An example or pseudocode could be helpful.**

P.S.
I'll learn about custom layers in the apis you mentioned earlier. Can't promise I will do it as fast as possible. You are always welcome to contribute!

**Comment by wewindy** [comment]
Yeah, I am very interested in this library, and wrote a blog with my native language in my spare time, and will take the time to study in depth.

I have some dev experience with OpenLayers & Cesium.js. OpenLayers use webgl tech to improve massive points showing performance well, and Cesium.js use `Primitive API` to create more 3d object with custom shader and render pipeline. (Well, Cesium's API is a bit complex...)

p.s.
A demo code for mapbox gl custom layer:

``` html
<script src='path/to/mapboxgl.js'></script>
<div id = 'map-container'></div>
<script>
  // show below.
</script>
```

``` js
const map = new mapbox.Map(/* params... */) 
const vbo = new Float32Array([...])

const lyr = {
  id: 'my-layer',
  type: 'custom',
  onAdd: (map, gl) => {
    // map is a variable which type is MapboxGL `Map`
    // gl is a variable which type is `WebGLRenderingContext`
    /*
      here, I'll use `gl` to init webgl buffer, shader program, vertex shader & fragment shader
     */
  },
  render: (gl, matrix) => {
     // gl is a variable which type is `WebGLRenderingContext`
     // matrix is a JavaScript array with 16 nums
     /*
        put the code that in every frame the mapboxgl engine render, 
        the custom layer should do, such as passing the matrix to the `uniform` to vertex shader, 
        and updating all vertex position, etc.
      */
  }
}

map.on('load', () => {
  if (map.getLayer('my-layer')) {
    map.removeLayer('my-layer')
    map.addLayer(lyr)
  }
})

```


or the full code can see [highlight custom layer in mapbox gl](https://docs.mapbox.com/mapbox-gl-js/example/custom-style-layer/)

And the API docs can be found in [mapbox gl custom layer interface](https://docs.mapbox.com/mapbox-gl-js/api/properties/#customlayerinterface)
