### ISSUE TITLE
Entities 'lclick' not always working

### ISSUE THREAD

**Issue by fridl8** [openglobus/openglobus#314]
We've set up a pretty basic globe with some entities as pins on it.  As a test to make sure I got it working correctly I set up a JS array to loop through and add 4 pins to the globe.

```
const osm = new og.layer.XYZ("OpenStreetMap", {
  attribution: 'Data @ OpenStreetMap contributors, ODbL',
  isBaseLayer: true,
  url: "//{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",
  visibility: true,
});

let globe = new og.Globe({
  "target": "og-container",
  "name": "Earth",
  "terrain": new og.terrain.GlobusTerrain(),
  "layers": [osm],
  "autoActivated": true
});

const items = [
  {id: 1, lat: 42.18380, lon: 3.7492, data: 'string1'},
  {id: 2, lat: 38.8950368, lon: -77.036542, data: 'string2'}
];

items.forEach((item, index) => {
  const entity = new og.Entity({
    name: item.id,
    lonlat: [item.lon, item.lat],
    billboard: {
      src: '/images/marker.png',
      size: [30, 35],
      offset: [0, 16] 
    }
  }); 

  const pointLayer = new og.layer.Vector(`pointLayer[index]`, {
    entities: [entity],
    async: false,
    nodeCapacity: 10000,
    clampToGround: true
  });
  pointLayer.events.on('lclick', () => {
    itemData = item.data;
    console.log(itemData);
  });
  pointLayer.addTo(globe.planet);
});
```

That's the code I'm currently using to add the 4 entities to the globe with a marker so they're clickable.  Only problem is that when we turn the globe far enough from where it initially loads the pins are no longer clickable until you move back to somewhere near the original starting point or to very specific spots on the globe.  Is it an issue with how I'm trying to set up the 'lclick' event or with how the layers load as you move to different spots on the globe?

**Comment by Zemledelec** [comment]
Try nodeCapacity:100000000 or something big. If it doesnt work, please give me real example and Ill check it up.

**Comment by Zemledelec** [comment]
...also try Vector layer property clampToGround: true.

**Comment by fridl8** [comment]
Added clamToGround and changed nodeCapacity to a larger number, but it didn't seem to have any noticeable effect.  I updated the code in the first post to show the globe setup, an example of the data, and the loop that I'm using.

Something I forgot to mention in the first post as well is that I'm using this in Ember, wasn't sure if that would create any issues with the globe or not.

**Comment by Zemledelec** [comment]
I've made your example here http://openglobus.org/tests/lclick/lclick.html, and it works fine.


https://user-images.githubusercontent.com/5452251/117791145-af1e6800-b252-11eb-987a-d7c3d7b31a7a.mp4

Could you show picking buffer in the moment when you can not click on the marker. Once you face with lclick issue enter a command in the console: **globe.renderer.setCurrentScreen("picking")** _(to return back enter globe.renderer.setCurrentScreen("**screen**"))_, you will see picture like this, where markers are available.

![image](https://user-images.githubusercontent.com/5452251/117791877-7337d280-b253-11eb-815e-8c132fe22c1b.png)

What browser do you use? 
Could you try your lclick bug example on another computer?

**Comment by fridl8** [comment]
We've tested it with Safari, Chrome, and Firefox on multiple computers and still have the issue.  Here's a picture of the picking buffer at the time when lclick isn't working.
![picking](https://user-images.githubusercontent.com/27429508/117830740-8a69c680-b239-11eb-8a10-2f028040ed2a.png)

None of the pins are clickable in that picture.  Turning the globe back to the right a little bit will make them clickable again.

**Comment by Zemledelec** [comment]
Very strange. Looks like it should work. Did you tested with my example? If not may be something with your css...

**Comment by Zemledelec** [comment]
...can I have a look at the real project?

**Comment by fridl8** [comment]
I played around with yours and it was working fine for me as well.  I think I'm going to continue to dig into our Ember and CSS to see if I can find out what is causing the issue.  I was hoping it was an issue with how I was adding the layers/entities because I haven't had much luck fixing it otherwise.
The project is behind a VPN and any local reproductions I can do are only accessible on the host machine.

It's looking like it may be an issue with our popups and CSS attached to them though, so I think I can safely say that it's definitely an issue on our end.  Thank you for the help!

**Comment by Zemledelec** [comment]
I suppose css somehow influences to mouse position inside your dom. It could be fixed inside openglobus api. Feel free to look into https://github.com/openglobus/openglobus/blob/71785cc7970759696b107db41ca3537a124ca801/src/og/input/MouseHandler.js#L59 and check the coordinates inside your container. Also here you can get picking color and compare with picking buffer https://github.com/openglobus/openglobus/blob/71785cc7970759696b107db41ca3537a124ca801/src/og/renderer/Renderer.js#L811. I could check it up for you, but I need your css.

Cheers!

**Comment by fridl8** [comment]
Just wanted to throw in a quick update, but the problem ended up being fixed by adding `myPopup.setCartesian3v(e.pickingObject.getCartesian());`.
I'm not too sure why I ended up excluding it from the original popup creating even though it's part of the example on the site and the example you showed me.
