### ISSUE TITLE
Unable to npm build for latest version

### ISSUE THREAD

**Issue by wizzed** [openglobus/openglobus#316]
I've gotten this error message while trying to build.

ModuleNotFoundError: Module not found: Error: Can't resolve '../res/night.js' in 'node_modules/@openglobus/og/src/og/scene'

I've used the package from npmjs.org to build, not sure if that's okay.

**Comment by pavletto** [comment]
Yes, I'm sorry about that. We only recently created an npm package and in an attempt to reduce the package weight, i accidentally added res to the exceptions. Now I fixed that - please check in version `0.8.9`.

**Comment by Zemledelec** [comment]
Suppose it's done?
