### ISSUE TITLE
Can this support type check with typescript and rewrite all Class into es6 mode?

### ISSUE THREAD

**Issue by wewindy** [openglobus/openglobus#328]
# Type check with typescript

When I use npm package, I found it is no code intelligence like other libs.

We can only use typescript to generate the `d.ts` declaration file from the existing jsDoc comments, instead of rewriting all the js files into ts files. In this way, you can get a better development experience, that is, the code intelligence hints.

# Rewrite class mode from constructor function to es6 class

I read source code and also found that some source code such as `LonLat.js`, `Extents.js`, etc. was written in es5 constructor function mode, not es6 class.

So I would like to rewrite them into es6 mode, it looks more modernly.

The jsDoc comments will remain intact.

**Comment by wewindy** [comment]
FYI @Zemledelec @pavletto

**Comment by pavletto** [comment]
I think `d.ts` is a good idea.

**Comment by Zemledelec** [comment]
The first reason I left **.prototype.** is that I'm not sure that classes works faster in js. Modules (or classes) such as Vec3, Quat, LonLat, Extent, Segment etc. are critical for engine (especially for contructing). So, before making a decision we must be sure that this or those approach doesn't make any negative affect on the **performance** of the engine.

The first step to make the decision is to prepare proper tests which shows that the classes signatures are satisfied the condition above.

**Comment by Zemledelec** [comment]
Replaced with https://github.com/openglobus/openglobus/issues/375
