### ISSUE TITLE
Empty globe and fill custom style? 

### ISSUE THREAD

**Issue by yeluoyunfei** [openglobus/openglobus#349]
Can I create an empty globe and fill my own style(e.g fill with different color)? I tried create an empty globe, but there always some shadom behind it:
![image](https://user-images.githubusercontent.com/8508499/129054815-4fefd228-f0be-43d4-b460-863e93c481b7.png)

**Comment by Zemledelec** [comment]
Hey! I've added two options(bool) in the Globe constructor useNightTexture, and useSpecularTexture. By default options both are true. Check it out!

P.S.
in the master branch

**Comment by yeluoyunfei** [comment]
Thanks @Zemledelec ! Great. it works! 
I was also adding it, but look like I am unable to send a pull request, Can you grant me the access?  I mean not for this time, if there are other issues  can I update it directly and send the pr in future? 
![image](https://user-images.githubusercontent.com/8508499/129334705-e7b0c61d-5329-4e07-81c2-f783cb253ece.png)

**Comment by Zemledelec** [comment]
As far as I know, you could do PR to openglobus from your fork. Try make a fork and then PR https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork
