### ISSUE TITLE
Option to set zoom in/zoom out limitation & option to set rotate range(E.g.  rotate 45° at max when rotate up and down)

### ISSUE THREAD

**Issue by yeluoyunfei** [openglobus/openglobus#350]
The default option can be current behavior(with no limitation). but user can custom it's own behavior as in some cases:

1. we can hardly see anything when globe is too small. 
2. user might get lost when rotate up and down/ left and right freely. 

DoD:

- [x]  add option for maximal and minimal camera altitude (above ellipsoid or terrain?)
- [x]  add options for camera angles above planet surface

**Comment by yeluoyunfei** [comment]
@Zemledelec  Can you share plan for this feature?

**Comment by Zemledelec** [comment]
Added Globe constructor options:
`minAltittude`
`maxAltitude`
`minSlope`
