### ISSUE TITLE
Not all canvas tiles are not get redraw when zoom in/out

### ISSUE THREAD

**Issue by yeluoyunfei** [openglobus/openglobus#351]
from below picture, we can see tile(15,6,4) and (0,6,4) are not get re-draw:
![image](https://user-images.githubusercontent.com/8508499/129705164-8406d62d-5351-496c-b5b7-323dd9246b96.png)

**Comment by Zemledelec** [comment]
Maybe they shouldn't be redrawn?

Try ToggleWireframe control 
`        globe.planet.addControl(new ToggleWireframe()); // from control/ToggleWireframe.js` and then press X key

And check that the segments(not tiles) are really deeper than they are. You will see "the division".

**Comment by Zemledelec** [comment]
However, if you wanted to see the same zoom tiles according to maximal camera altitude, so I could add an option.

This is ok, this is how level of detail works:
![image](https://user-images.githubusercontent.com/5452251/129908999-b548746d-5f35-4fd2-986c-80893e2ce1ab.png)

**Comment by Zemledelec** [comment]
This is also ok:
![image](https://user-images.githubusercontent.com/5452251/129909350-8c5d5074-424f-4ff8-8991-cb590abfdca2.png)

**Comment by yeluoyunfei** [comment]
That's make sense. thanks!
