### ISSUE TITLE
Support custom globe view setting when switch from other layer?

### ISSUE THREAD

**Issue by yeluoyunfei** [openglobus/openglobus#353]
For some scenario, it is likely that user switching to 3D map layer from other layer( 2D map layer or 3D map)  in the previous layer, user has  specified the location, when switch to 3D layer, we expect that view is  also zooming to the specific  location(zoom level can be controlled ).  similar like below snapshot.  
![image](https://user-images.githubusercontent.com/8508499/130719863-212e5498-8f48-4f1e-9bcb-4489db9696af.png)

**Comment by Zemledelec** [comment]
Sorry, I don't get it, could you describe a case by steps, please.

**Comment by Zemledelec** [comment]
@yeluoyunfei  need more details, please.
viewExtent, flyLonLat?

**Comment by yeluoyunfei** [comment]
Yes. I found a way for this. close it
