### ISSUE TITLE
Option to make the globe visible to user after all the canvas in the whole globe(except pole?) is ready and expose a way to let the developer know when rendering is complete 

### ISSUE THREAD

**Issue by yeluoyunfei** [openglobus/openglobus#355]
currently when user rotate, there is visible experience gap before newly rotated view ready. need an option to make the globe visible to user after all the canvas in the whole globe is ready. then it will have smooth user experience when rotate. also need expose a way to let the developer know when rendering is complete so that they can do some other job.

**Comment by Zemledelec** [comment]
I'm not sure that it is possible 100% especially making the globe visible to user after all the canvas in the whole globe is ready, but:

1. I can implement something like "rendercomplete" event, when every segment on the screen is completed, and nothing is loading.
2. I can add option that makes whole globe rendered when you see whole globe sphere from far space, it will helps to avoid empty tiles when user rotates the globe.

**Comment by Zemledelec** [comment]
Hey @yeluoyunfei rendercomplete is enough?

**Comment by yeluoyunfei** [comment]
Yes. I think it's ok for currently
