### ISSUE TITLE
Missing CSS entry in package.json exports

### ISSUE THREAD

**Issue by gnuletik** [openglobus/openglobus#362]
When importing the CSS file with a JS bundler like this : 
```js
import '@openglobus/og/css/og.css'
```

It throws an error with Vite :
```
Missing "./css/og.css" export in "@openglobus/og" package
```
And with Snowpack : 
```
Error: Package "@openglobus/og" exists but package.json "exports" does not include entry for "./css/og.css".
```

The package.json's exports configuration should include this line: 
```
   "./css/og.css": "./css/og.css" 
```

but it does not :
https://github.com/openglobus/openglobus/blob/942483f68ca0409584023e6213e0e6df7bcf307f/package.json#L31-L40

**Comment by Zemledelec** [comment]
Thanks! Added in v0.10.4!

Verifiez, sil vouz plait!

P.S.
It looks like you could be a contributor @gnuletik !))

**Comment by gnuletik** [comment]
Thanks!
It works great :)
