### ISSUE TITLE
Globe edge bounce

### ISSUE THREAD

**Issue by yeluoyunfei** [openglobus/openglobus#367]
see snapshot. the edge will bounce will rotate:
![image](https://user-images.githubusercontent.com/8508499/133576900-33c4a05a-d00a-4b34-b2be-60982b58ad95.png)
![image](https://user-images.githubusercontent.com/8508499/133577353-c0d11949-ad2b-4c23-8054-6997def37d09.png)

**Comment by Zemledelec** [comment]
Please check up the last master!
