### ISSUE TITLE
Render delay in pole area

### ISSUE THREAD

**Issue by yeluoyunfei** [openglobus/openglobus#397]
There is visible delay when rotate to pole area.

**Comment by Zemledelec** [comment]
Ok, little explanation, that there is no bug, it is normal behavior. I'm going to make pole areas getting always rendered when traversing pole tree. It could help to diminish delay effect.

**Comment by Zemledelec** [comment]
@yeluoyunfei,  check this up, please! Already in master.

**Comment by Zemledelec** [comment]
@yeluoyunfei close?

**Comment by yeluoyunfei** [comment]
Yes.
