### ISSUE TITLE
remove callback from renderer event

### ISSUE THREAD

**Issue by alacst** [openglobus/openglobus#426]
Hey,

is it possible to remove a callback from the renderer events?
I'd like to create a "lclick" event and remove it once its fired. 

`globus.planet.renderer.events.on("lclick", (e) => {
                   foo(e);
                });`
I'd also like to remove this foo() from the events only.
Is there any way to do this?

Thank you!

**Comment by Zemledelec** [comment]
Hi @alacst!
You should do like this:
```
function _onLClick(e) { ... }
globus.planet.renderer.events.on("lclick", _onLClick);
globus.planet.renderer.events.off("lclick", _onLClick);

```
Also, third parameter of on function is a sender, for instance:
```
class Boo {
...
_onLClick = (e) => { ... }
globus.planet.renderer.events.on("lclick", _onLClick, this);
globus.planet.renderer.events.off("lclick", _onLClick);
}
```

**Comment by alacst** [comment]
hey @Zemledelec,

I could not test it yet, but I've checked the code for the event.off part:

`  

     /**
     * TODO: DOESNT WORK!!!
     * @param {any} name      
     * @param {any} callback      
     */  
    off(name, callback) {      
        if (name === "keypress" || name === "charkeypress" || name === "keyfree") {      
            this._keyboardHandler.removeEvent(name, callback);      
        } else {      
            super.off(name, callback);      
        }      
    }`   

the TODO comment made me suspicious. Is that working?

**Comment by alacst** [comment]
it seems to be working.

**Comment by Zemledelec** [comment]
@alacst close?

**Comment by alacst** [comment]
thank you!
