### ISSUE TITLE
Improve visual delay when switch new layer with preloading

### ISSUE THREAD

**Issue by yeluoyunfei** [openglobus/openglobus#439]
when change to a newly added everything is lagging(there are visible empty tiles when rotate globe) even I make the globe visible after render complete/loaded.
One workaround is to pre-load all layers when initialize the globe, using set opacity when switch layer , it works when there are only few layers, but when layer number increase, this is not scalable to pre-load all layers.

**Comment by Zemledelec** [comment]
MR https://github.com/openglobus/openglobus/pull/460

**Comment by Zemledelec** [comment]
It's done  for now. Next we will talk in the https://github.com/openglobus/openglobus/issues/459
