### ISSUE TITLE
Make constrained extent in Globe

### ISSUE THREAD

**Issue by jhjojhjo** [openglobus/openglobus#440]
Thanks for your nice works.

I am applying only some areas of the terrain data, and they are converted into ddm files.
However, when they are expressed in the globusTerrain, it looks like the picture.

how to flatten the edge ?

Is it possible to view(or constrain)  only the specific extent in globe.
how can I  view terrain in extent area only ? 
is there the example
![test](https://user-images.githubusercontent.com/95408636/144552720-016a25f4-a0ba-423c-b03b-f31bffc8fb94.png)
 ?

**Comment by Zemledelec** [comment]
Hi @jhjojhjo! I'd like to propose you do not use ddm (I'm thinking to make it deprecated) now, and use ratsers the same way as mapbox do with rasterio. Unfortunately I have not made a good tutorial (in progress) yet, but take a look on MapboxTerrain provider here http://openglobus.org/examples/mapboxTerrain/mapboxTerrain.html and the good tutorial from here https://github.com/syncpoint/terrain-rgb but for EPSG:3857 (WebMercator) tiles - how to create you own tiles suitable for MapboxTerrain provider you need to set a few parameters in constructor. And you will get any terrain you want:)

Welcome to ask any question!

P.S. 
 It could be tricky first time, but next time it is easy like one two three with gdal and rasterio)), tutorial is on the way!

**Comment by jhjojhjo** [comment]
Thanks. 
good advice to me.

I need to think view extent, in case of having partially  terrain.
can you support it ?

**Comment by Zemledelec** [comment]
@jhjojhjo 
Could you be more specific, please? 
What terrain source files do you use?
As far as I understand you need to display terrain data, so:

There are two ways:
1) Create rasterio elevation tiles from geoTiff, and you will see the whole geotiff you want. You can edit your geotiff with qgis and get any bounds you want.
2) I could add an option for bounds to terrain provider and you will get visible terrain in bounds of the extent.

The first is already you can work with now, but the second is need to be work with.

I'd recommend you create rasterio elevation tiles first and then use it inside MapboxTerrain provider.

Do you have any problem with rasterio or MapboxTerrain provider?

**Comment by jhjojhjo** [comment]
Thanks.
I will try your recommendation. 

Here is question on Extent. 
The GlobusTerrain doesn't seem to support extent option.
Although the terrain was limited to [ 125.0, 33.0, 130.0, 40.0 ], the other areas out of the area seems to be displayed out as well.
In my opinion, terrain data outside the extent should not be imported by network.
I give the attachment.
Is my test  wrong?
[test.zip](https://github.com/openglobus/openglobus/files/7682398/test.zip)

**Comment by Zemledelec** [comment]
True, og terrain provider doesnt support extent option.
Ok, you want the extent option, right? :)
It's possible, but need time. Right now you can use geotif as is like here on the right screen:

http://openglobus.org/examples/multipleViewports/multipleViewports3.html

**Comment by jhjojhjo** [comment]
I think the loading speed of mapbox-rgb is lower than ddm.
I am novice on geo-conversion.
My terrain source is ESPG 5186.

**Comment by Zemledelec** [comment]
> I think the loading speed of mapbox-rgb is lower than ddm.

ddm size 33x33x4 bytes, rasterio elevation tiles(png) 256x256x4 bytes. But, rasterio tiles is convenient and looks nice. There are good tools to work with geotif sources such as gdal, rasterio, gdal2tiles etc.

> My terrain source is ESPG 5186.

Also, you can easily convert any proj to EPSG:3857 (suitable for openglobus terrain provider) with gdal.

ddm is lack of the features you can have already with rasterio tiles, such as we cant make ddm from geotif.

**Comment by jhjojhjo** [comment]
I had converted my terrain to Mapbox-rgb tiles.
256x256 terrain tiles are so slow. 
The mapbox-rgb 64x64x4 PNG  tiles made by gdal2tiles are maybe not supported in MapBoxTerrain.js .
Is it right ?

**Comment by Zemledelec** [comment]
1) Try MapboxTerrain provider constructor options
```
...
        plainGridSize: 64, //or 32
        imageSize: 64
...
```
2) What do you mean slow? Slow for rendering or slow for loading?

**Comment by jhjojhjo** [comment]
that's means 'rendering time'. 
I think ddm is better than MB.

**Comment by Zemledelec** [comment]
So, if you have problem with rendering time(frame per second), I'd suggest you change  gridSizeByZoom for terrain constructor, and see the difference. You should use power of two values in the array.

ddm is better that png in one, that ddm is 33x33 grid and heights on a border of every tile are equal. It means that you do not need to equalize elevations of two neighbour nodes for the ddm terrain provider.

![image](https://user-images.githubusercontent.com/5452251/145986496-550799f1-4c49-4416-896a-e0ae6797e03f.png)

This is an abstraction of how elevation tile work with ddm and png for png image 4x4 and ddm 5x5

```
 gridSizeByZoom: [
      64, 32, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 4, 4, 4
  ] 
```

**Comment by Zemledelec** [comment]
My dream is to improve gdal2tiles.py to handle png the same way as ddm do:)

**Comment by jhjojhjo** [comment]
thanks for your kindness.
what does mean option gridSizeByZoom ?
i don't understand it.

i hope to come true your dream.

**Comment by Zemledelec** [comment]
Thanks!)) gridSizeByZoom is an array with elevation grid sizes. Each index matches to tile zoom level, each value - is size of grid with elevation data. In other words - gridSizeByZoom is array of levels of details. Each size must be a power of two number such as 2,4,8,16 etc. The bigger value the less performance, but more detailed, also the value mast be less or equall than imageSize value,
