### ISSUE TITLE
add/remove geoObject 

### ISSUE THREAD

**Issue by jhjojhjo** [openglobus/openglobus#446]
Thanks for this fine works.

I am working on adding a geoObject.
That is planning to left-click to add, right-click to remove.
When the attached  JavaScript is first executed, addition and removal are executed well.
However, after adding a few geoObjects, removing all of them, and adding a geoObject again, the geoObject cannot be rendered on screen.
It is strange.

The codes is attached!
[a.zip](https://github.com/openglobus/openglobus/files/7673503/a.zip)

Thanks 

p.s. It is good in case of applying billboard, instead of geoObject.

**Comment by Zemledelec** [comment]
Created branch:
https://github.com/openglobus/openglobus/issues/446

FYI @pavletto

**Comment by pavletto** [comment]
@jhjojhjo thanks for report! Fix it. @Zemledelec create PR #447

**Comment by jhjojhjo** [comment]
Thanks for reply.
How rapid it is!

**Comment by Zemledelec** [comment]
@jhjojhjo could you test from here?
PR https://github.com/openglobus/openglobus/pull/447
