### ISSUE TITLE
how to add heatmap to og

### ISSUE THREAD

**Issue by jhjojhjo** [openglobus/openglobus#456]
Hi. Happy new years.
I tried to plug open sourced webgl-heatmap in og.
But I could not add the heatmap to layer, like tile image layer on specific area.
It seems that the input data of the heatmap should be Lon/Lat coordinate data rather than pixel data.

Can you help to convert pixel to Lon/Lat, add the heatmap in layer style ?
[test-heatmap.zip](https://github.com/openglobus/openglobus/files/7800546/test-heatmap.zip)

**Comment by Zemledelec** [comment]
Happy New Year, @jhjojhjo!

First, you should understand how CanvasTiles works. Here is an example http://openglobus.org/examples/canvasTiles/canvasTiles.html

Second, you have to draw pixels inside your html5 tiles, where each tile has web mercator projection extent. Try to debug CanvasTiles draw handler.

**Comment by yeluoyunfei** [comment]
Hey. @jhjojhjo , Globus is doing great support heatmap. this is an production example using globus: https://www.msn.com/en-us/weather/maps/temperature/in-Coulee-136,SK?zoom=3&3d=1&loc=eyJsIjoiQ291bGVlIDEzNiIsInIiOiJTSyIsInIyIjoiRGl2aXNpb24gNyIsImMiOiJDYW5hZGEiLCJpIjoiQ0EiLCJnIjoiZW4tdXMiLCJ4IjoiLTEwNy40ODEiLCJ5IjoiNTAuMDcifQ%3D%3D&ski=1

**Comment by jhjojhjo** [comment]
wow! nice job.
How did globus  implement that?

I don't think it's a heatmap?

**Comment by jhjojhjo** [comment]
> Happy New Year, @jhjojhjo!
> 
> First, you should understand how CanvasTiles works. Here is an example http://openglobus.org/examples/canvasTiles/canvasTiles.html
> 
> Second, you have to draw pixels inside your html5 tiles, where each tile has web mercator projection extent. Try to debug CanvasTiles draw handler.

**Comment by Zemledelec** [comment]
The answer is here:

First, you should understand how CanvasTiles works. Here is an example http://openglobus.org/examples/canvasTiles/canvasTiles.html

Second, you have to draw pixels inside your html5 tiles, where each tile has web mercator projection extent. Try to debug CanvasTiles draw handler.

@jhjojhjo do you have questions for CanvasTiles?

**Comment by Zemledelec** [comment]
Here some useful examples https://github.com/openglobus/openglobus/issues/111

Lets go there for further discussion.
