### ISSUE TITLE
Better code compatibility with TypeScript

### ISSUE THREAD

**Issue by tbo47** [openglobus/openglobus#479]
Here is a list of problem we would have if we switch the code to typescript:

Property 'moveend' does not exist on type 'Events'
https://github.com/openglobus/openglobus/blob/master/src/og/camera/Camera.js#L183

Property 'viewchange' does not exist on type 'Events'
https://github.com/openglobus/openglobus/blob/master/src/og/camera/Camera.js#L280

**Comment by Zemledelec** [comment]
FYI @pavletto

**Comment by Zemledelec** [comment]
...I'd say get closer to a kind of code which suits for ts hadlers:)

**Comment by Zemledelec** [comment]
Replaced to https://github.com/openglobus/openglobus/issues/657
