### ISSUE TITLE
Mouse events at the Entity

### ISSUE THREAD

**Issue by Babeev** [openglobus/openglobus#488]
Is there a way to bind mouse event to an Entity? I want to add 'mouseenter' or 'click' event handler to billboard and then show popup on this billboard.
I couldn't find a way in the documentation: https://www.openglobus.org/api/module-og_entity_Entity-Entity.html

**Comment by pavletto** [comment]
`EntityCollection` has mouse events. You can see how it works in [billboard exemple](http://openglobus.org/examples/billboards/billboards.html) ([billboard code](https://github.com/openglobus/openglobus/blob/master/examples/billboards/billboard.js))

**Comment by Babeev** [comment]
Thank you very much
