### ISSUE TITLE
Error with the entity label

### ISSUE THREAD

**Issue by Babeev** [openglobus/openglobus#489]
<img width="440" alt="Снимок экрана 2022-03-05 в 12 18 53" src="https://user-images.githubusercontent.com/64578266/156869331-7725156f-894b-46ee-8362-8a5c640c3769.png">

https://user-images.githubusercontent.com/64578266/156869436-93555c38-d0c5-4c08-86d6-80cdfcad4018.mov

Please, explain something, I trying to add label to billboard. As image i chose a plain circle png, and change color in dependence of data. But at some scales label is over image, some scales image is over label. How can i fix this, may be there is a z-index option?

**Comment by pavletto** [comment]
Yep, problem with `z-index`. You can try set third parameter for property `offset`

**Comment by Zemledelec** [comment]
I'll answer more specifically in the https://github.com/openglobus/openglobus/issues/491
