### ISSUE TITLE
Problem with "aground" parameter

### ISSUE THREAD

**Issue by Babeev** [openglobus/openglobus#491]
Please tell me how I can solve the problem with the location of the entity exactly on the ground of the map? Initially, I create an empty collection of entities and add it to the planet. 
```
const collection = new EntityCollection({
  entities: [],
})
collection.addTo(globe.planet)
```

Then I add an array of entities to the collection of entities.
`collection.addEntities(newEntities)`

Then I add the collection to the planet.
`collection.addTo(globe.planet)`

If I don't specify the third parameter in billboard offset, then the map hides the entities after loading. 
<img width="614" alt="Снимок экрана 2022-03-11 в 17 10 49" src="https://user-images.githubusercontent.com/64578266/157851246-8ebcc131-41f1-4dce-9c6e-bd8f87f187be.png">

https://user-images.githubusercontent.com/64578266/157851595-5c8233f0-583c-485b-95af-c3dc9da8dab3.mov

If I specify a positive third parameter, for example "99", then the behavior changes slightly. 

https://user-images.githubusercontent.com/64578266/157852138-9c49e074-d196-4854-8f1a-ecfaec853fcf.mov

With a negative parameter, for example "-99", everything looks good at first, but when I zoom in to the entity and change the camera angle, it can be seen that the entity changes its position, as if it is deep underground.

https://user-images.githubusercontent.com/64578266/157852558-445bb79e-523b-4385-b5a2-46f731537cf9.mov

Here are my globe and layer:
<img width="486" alt="Снимок экрана 2022-03-11 в 17 49 53" src="https://user-images.githubusercontent.com/64578266/157853362-c5d56a0d-1867-41d8-b3ac-67ce82760fbd.png">
<img width="463" alt="Снимок экрана 2022-03-11 в 17 50 10" src="https://user-images.githubusercontent.com/64578266/157853969-c1857f47-88a1-43ae-bc6a-b962bdecdf82.png">

Without considering the label, how can entities be positioned exactly on the ground?

**Comment by Zemledelec** [comment]
Hi! This is very good question! I'll try to explain...

**Comment by Zemledelec** [comment]
Third parameter is Z coordinates offset (depth buffer offset). It helps to sort labels and billboards manually. For instance you want to place background billboard under a label, both coordinates are equal. You could use Z offset for label -1, and for billboard Z = 0. Also, there is an option for `Vector/EntityCollection` objects `polygonOffsetUnits`, you could use it to sort objects the way you want for all objects in collection. 

For ground labels use option from the example http://openglobus.org/examples/billboardsOnTheGround/billboardsOnTheGround.html
also if you want offset above ground use `relativeToGround `as number in meters, also `relativeToGround `affects on entity.altitude for only entity.

P.S.
Use Vector layers, not EntityCollection. If you don't need clicking on layer objects, use pickingEnabled: false.

**Comment by Zemledelec** [comment]
...FOR 3 vide use polygonOffsetUnits: -10000 for instance.

**Comment by Zemledelec** [comment]
Close the issue?

**Comment by Babeev** [comment]
Yes, thank you very much!
