### ISSUE TITLE
[Reporting Bugs] When I move the map on the touch screen of my mobile phone, it will cause a bug.

### ISSUE THREAD

**Issue by magicbing** [openglobus/openglobus#492]
![image](https://user-images.githubusercontent.com/12853293/159156409-3b4fb7f4-622d-416d-958e-d5b087bf4663.png)
When I move the map on the phone, this error occurs, and the map cannot be moved after that.

The code causing the error is in this file TouchNavigation.js, these two functions onDraw and onTouchMove.
```                    
                     cam._v = rot.mulVec3(cam._v);
                     cam._u = rot.mulVec3(cam._u);
                     cam._n = rot.mulVec3(cam._n);
```

'this.renderer.activeCamera' somethimes lose '_v'  or '_n'.

I compared the code of MouseNavigation.js，and then replaced the code.
```
                    // cam._v = rot.mulVec3(cam._v);
                    // cam._u = rot.mulVec3(cam._u);
                    // cam._n = rot.mulVec3(cam._n);
                    cam._u = rot.mulVec3(cam._u);
                    cam._r = rot.mulVec3(cam._r);
                    cam._b = rot.mulVec3(cam._b);
```

After that it works, but I still haven't figured out the reason for the problem.

**Comment by Zemledelec** [comment]
Thanks! Taken.

**Comment by pavletto** [comment]
Fixed
