### ISSUE TITLE
Safari 15.1 CORS issue, Safari 15.4 completely broken

### ISSUE THREAD

**Issue by mxmtsk** [openglobus/openglobus#500]
I've noticed with the official examples two issues in Safari.

On **Safari 15.1**, the globe works, but the tiles cannot be loaded due to a CORS issue ( i believe

> [Error] Failed to load resource: Cross-origin redirection to https://a.tile.openstreetmap.org/4/5/8.png denied by Cross-Origin Resource Sharing policy: Origin http://openglobus.org is not allowed by Access-Control-Allow-Origin. (8.png, line 0)

>[Error] Cross-origin redirection to https://c.tile.openstreetmap.org/3/0/5.png denied by Cross-Origin Resource Sharing policy: Origin http://openglobus.org is not allowed by Access-Control-Allow-Origin.

On **Safari 15.4** however, the whole rendering of the globe seems to be broken (the screenshot is the nicest result I got, sometimes it disappears completely, no apparant issues in the console though):
<img width="1920" alt="Screenshot 2022-04-19 at 11 20 47" src="https://user-images.githubusercontent.com/4848184/163972922-d989293c-094c-4968-9786-b2e045c238e6.png">

**Comment by Zemledelec** [comment]
Could someone else check that it's good now?

**Comment by mxmtsk** [comment]
Sorry didn't saw your earlier comment in December. Just checked with Safari 15.6 and it looks good on that one. :)
