### ISSUE TITLE
setStrokeColorArr undefined

### ISSUE THREAD

**Issue by dienthai2022** [openglobus/openglobus#505]
In Geometry.js   line 230     

Looks like setStrokeColorArr is undefined?

`this._handler && this._handler.setStrokeColorArr(this, c);`

I changed to

`this._handler && this._handler.setLineStrokeColorArr(this, c);`

**Comment by Zemledelec** [comment]
Hi! Looks like it was missed during a refactoring. Thanks!

Please take a look MR https://github.com/openglobus/openglobus/pull/506
