### ISSUE TITLE
Provide good atmosphere scattering algorithm

### ISSUE THREAD

**Issue by yeluoyunfei** [openglobus/openglobus#510]

**Comment by Zemledelec** [comment]
1) Looks interesting
http://www.thetenthplanet.de/archives/4519
https://github.com/Dimev/atmosphere-shader
https://www.shadertoy.com/view/wlBXWK

2) Take a look around Bruneton: https://ebruneton.github.io/precomputed_atmospheric_scattering/

**Comment by Zemledelec** [comment]
Bounded with https://github.com/openglobus/openglobus/issues/576

**Comment by Zemledelec** [comment]
MILESTONE ISSUE https://github.com/openglobus/openglobus/issues/598

**Comment by Zemledelec** [comment]
Done with v0.15.0
