### ISSUE TITLE
Improve terrain collision function

### ISSUE THREAD

**Issue by Zemledelec** [openglobus/openglobus#544]
Right now, it uses a comparatively fast but (sometimes) not precise terrain collision method.

**Comment by martyrion** [comment]
Where is the code for this function?

**Comment by Zemledelec** [comment]
Hey @martyrion! There is a bug "jumping" on edges between tiles where terrain exists and does not exists:
https://user-images.githubusercontent.com/5452251/184507078-b4ddaef3-4089-4ea2-9425-a775616ebbca.mp4

Example:
http://openglobus.org/examples/multipleViewports/multipleViewports3.html

Code:
https://github.com/openglobus/openglobus/blob/fd88ca526eb3e1f3bbe1cc0dac36ec10ff9475bb/src/og/camera/PlanetCamera.js#L615

**Comment by Zemledelec** [comment]
I improved some terrain collision a few weeks ago, and I tried to use each triangle to collide and it worked very slowly, but I fixed suddenly jumping when flying over holes - no data values. I think closing the issue, it's not important right now.
