### ISSUE TITLE
Custom Terrain RGB tiles & Elevation control

### ISSUE THREAD

**Issue by martyrion** [openglobus/openglobus#547]
Hello, I have produced some custom Terrain RGB tiles,  and modified the mapboxTerrain.html example file, to read them from my server.

`maxGridSize: 256,
            "terrain": new MapboxTerrain('my-dem',{
               url: "../../../assets/gis/dem/{z}/{x}/{y}.png" 
            }),`

The terrain **looks pretty good** - it is responding to reality.
Nevertheless the elevation indicator is not responding to reality. **All indications are from 16-18m only!**

Where could the problem be?

- my dem file?
- my tiles creation?
- openglobus library?

**The mapboxTerrain.html as provided, shows the elevation very good.**

**Comment by martyrion** [comment]
I can also see on the console, that OG is trying for some reason to read to **zoom level 17 while I am currently zooming from lvl 8 to lvl 11, for example.**

![image](https://user-images.githubusercontent.com/63229987/183677213-b35a870a-0a2d-4981-b04e-fdfddb01f399.png)

**Comment by Zemledelec** [comment]
> I can also see on the console, that OG is trying for some reason to read to **zoom level 17 while I am currently zooming from lvl 8 to lvl 11, for example.**
> 
> ![image](https://user-images.githubusercontent.com/63229987/183677213-b35a870a-0a2d-4981-b04e-fdfddb01f399.png)

It means that `CoordinatesControl `is going for elevation data. It means that `maxZoom `is equal to 17 for the layer. If you need you can change maxZoom to any zoom you need, `maxZoom `- is max available tile zoom for the terrain provider. For instance, openglobus `maxZoom `= 14, for high-resolution terrain I use 17-19 zoom levels. 

```
let highResTerrain = new MapboxTerrain(null, {
            maxZoom: 19,
            url: "//terrain.openglobus.org/public/highRes/{z}/{x}/{y}.png",
            gridSizeByZoom: [
                64, 32, 16, 8, 8, 8, 8, 16, 16, 16, 16, 16, 32, 64, 128, 128, 64, 32, 16, 8, 4
            ],
            geoidSrc: "./egm2008-1.pgm"
});
```

,where `gridSizeByZoom` level of detail, and if you want super detailed picture use  128, or 256, but in this case you need to play with `imageSize: 256, plainGridSize: 256`, where imageSize is you imageSize, and plainGridSize is maximal available LOD.

**Comment by Zemledelec** [comment]
> Hello, I have produced some custom Terrain RGB tiles, and modified the mapboxTerrain.html example file, to read them from my server.
> 
> `maxGridSize: 256, "terrain": new MapboxTerrain('my-dem',{ url: "../../../assets/gis/dem/{z}/{x}/{y}.png" }),`
> 
> The terrain **looks pretty good** - it is responding to reality. Nevertheless the elevation indicator is not responding to reality. **All indications are from 16-18m only!**
> 
> Where could the problem be?
> 
> * my dem file?
> * my tiles creation?
> * openglobus library?
> 
> **The mapboxTerrain.html as provided, shows the elevation very good.**

Hey, @martyrion

1) If you use elevation above ellipsoid WGS84, you need to disable geoid with `geoidSrc: null` in the `MapboxTerrain`

```
    terrain: new MapboxTerrain("nogeoid", {
        geoidSrc: null
    }),
```

2) Set actual `maxZoom ` option

3) It depends on data of course

Btw, coordinates control shows elevation above the ellipsoid (not sea level).

**Comment by martyrion** [comment]
Thanks a lot for the detailed explanation @Zemledelec!
