### ISSUE TITLE
How to update polyline coordinates

### ISSUE THREAD

**Issue by iou84** [openglobus/openglobus#550]
Dear sirs,

I am trying to show a polygon on the map (with four coordinates each time) which I want to update its coordinates every time i get the new ones but i have not managed to succeed. I always get an error.

I have tried to define my coordinates as below (one for each coordinate):

let cor4 = new LonLat(lon4,lat4);

Then created an array with all four coordinates:
grid = [cor1,cor2,cor3,cor4];

and then try to update pathlonlat:

polylineEntity.polyline.setPathLonLat(grid,false); 

but i get a strange error about lonlat is undefined

Thank you in advance

**Comment by Zemledelec** [comment]
Hi @iou84!

Take a look at an example here http://openglobus.org/examples/polylineOnTheGround/polylineOnTheGround.html, line 101.
Put your array inside another, like [[c0, c1, c2], [v1, v2, v3], ....] it means that the path consists of multiple lines the same way as the grid in the example above.

**Comment by iou84** [comment]
Dear Zemledelec,
Thanks for the response

Unfortunately I have tried your advice but with no results

I have tried to replicate the polyline example but with a polygon instead of circle as per the example below:
function createGrid(coor1, coor2, coor3, coor4) {
    let grid = [];
    grid.push(coor1);
    grid.push(coor2);
    grid.push(coor3);
    grid.push(coor4);      
               
    return grid;
};

let p1 = new LonLat(34.4, 35.73);
let p2 = new LonLat(34.4, 35.90);
let p3 = new LonLat(34.2, 35.73);
let p4 = new LonLat(34.2, 35.90);

const polylineEntity = new Entity({
    'polyline': {
        'pathLonLat': createGrid(p1,p2,p3,p4),
        'thickness': 3,
        'color': "rgba(68, 157, 205, 0.92)",
        'isClosed': false
    }
});

const pointLayer = new Vector("points", {
    'clampToGround': true,
    'entities': [
        polylineEntity
    ],
    'async': false
});

const globe = new Globe({
    "target": "globus",
    "name": "Earth",
    "terrain": new GlobusTerrain(),
    "layers": [osm]
});

window.globe = globe;
 But as a result i get this error:
<img width="1280" alt="Screenshot 2022-08-14 172112" src="https://user-images.githubusercontent.com/38797166/184548992-7eb32fe1-e407-4385-bff4-ef51514f7be8.png">

Any advice will be appriciated

I think is the way i am declaring the polyline??

Thanks in advance

**Comment by iou84** [comment]
Sorry

**Comment by Zemledelec** [comment]
Should be: `'pathLonLat': [createGrid(p1,p2,p3,p4)],`

**Comment by iou84** [comment]
Dear Michael,

Thanks again for the interest and the response and for your help
Below there is one working example:
 
<html>

<head>
    <title>OpenGlobus - Earth planet</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="../../css/og.css" type="text/css" />
</head>

<body>
    <div id="globus" style="width:100%;height:100%"></div>
    <script type="module">
        'use strict';

        import { Entity } from '../../src/og/entity/Entity.js';
        import * as math from '../../src/og/math.js';
        import { Globe } from '../../src/og/Globe.js';
        import { LonLat } from '../../src/og/LonLat.js';
        import { Vec3 } from '../../src/og/math/Vec3.js';
        import { Quat } from '../../src/og/math/Quat.js';
        import { XYZ } from '../../src/og/layer/XYZ.js';
        import { Vector } from '../../src/og/layer/Vector.js';
        import { GeoImage } from '../../src/og/layer/GeoImage.js';
        import { GlobusTerrain } from '../../src/og/terrain/GlobusTerrain.js';

     
     
        
function createGrid([[coor1], [coor2], [coor3], [coor4]]) {
    let grid = [];
    let coor = [];
    grid.push(coor1);
    grid.push(coor2);
    grid.push(coor3);
    grid.push(coor4);      
     
    coor.push(grid);
    return coor;
};

let p1 = [34.4, 35.73 ];
let p2 = [34.4, 39.73 ];

let p3 =[34.4, 36.73 ];

let p4 = [35.4, 35.73 ];
 

const myLine = new Entity({
    'polyline': {
        'pathLonLat': createGrid([[p1],[p3],[p2],[p4]]),
        'thickness': 8,
        'color': "rgba(225, 157, 205, 0.92)",
        'isClosed': true
    }
});

const pointLayer = new Vector("points", {
    'clampToGround': true,
    'entities': [
        myLine
    ],
    'async': false
});
        




let np1 = [ 35.33 , 34.33];
let np2 = [36.33 , 34.33];
 let np3 = [35.33 , 35.33];
 let np4 = [36.33 , 35.33];
  

 myLine.polyline.setPathLonLat(createGrid([[np1],[np2],[np3],[np4]], true));   


        var osm = new XYZ("OpenStreetMap", {
            isBaseLayer: true,
            url: "//{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",
            visibility: true,
            attribution: 'Data @ OpenStreetMap contributors, ODbL'
        });

       
        const globe = new Globe({
            "target": "globus",
            "name": "Earth",
            "terrain": new GlobusTerrain(),
            "layers": [osm, pointLayer]
        });
        window.globus = globe;

    </script>
</body>

</html>
