### ISSUE TITLE
Bug in Layer Switcher

### ISSUE THREAD

**Issue by martyrion** [openglobus/openglobus#553]
I found a bug in Layer Switcher. I believe it existed before my last pull request.

Steps to reproduce:

1. Select an overlay to show
2. Switch between 4 different baseman's

> if you continuously switch between 2 or three basemaps, the behaviour is ok

The overlay is gone.

**Comment by Zemledelec** [comment]
There was a bug, I fixed a few days ago. Try the last master.

**Comment by martyrion** [comment]
Thanks a lot Michael!
