### ISSUE TITLE
Openglobus UI discussion

### ISSUE THREAD

**Issue by martyrion** [openglobus/openglobus#554]
Hello!

I think that it would be very nice to have a tool palette for OG. Thinks that come to my mind are:

- Layer Switcher
- Ruler
- GeoImage Dragger ON/OFF button
- Drawing tools (square, circle, sphere etc)
- Add marker

I think the heart of the UI should be the **Layer Switcher control**. It needs to perform the following:

- Change visibility (exists)
- Zoom to extend (exists)
- Lock/unlock layer for operations- only one allowed each time
- Drag and drop to change order ==> zIndex
- Create new layer
- Save changes to layer

What do you think?
I could do most of the work with some help - being javascript beginner.
Starting point could be a sketch of the UI in Figma.

@Zemledelec? and everybody?

**Comment by Zemledelec** [comment]
This is a very good idea, @martyrion !

1) As you said, each control could have a button, like layerSwitcher. 
2) I'm not sure about locking a layer, what is it?
3) As far as I understand you are talking about drag and drop onside layerSwitcher?
4) It could be, also be a control for XYZ, WMS, layers, also terrain providers
5) I don't understand how a layer saving could be.

**Comment by martyrion** [comment]
Hey @Zemledelec ,

2. Well, if I have 5 overlays and I want to create a new marker, in which overlay will that be placed? A more precise expression - instead of "locking" - should be "select".
3. I almost have an example ready and soon send a video.
4. I agree!
5. For example if I drag a geo-image to correct position, maybe hit a "save" button and save correct position to a file

**Comment by Zemledelec** [comment]
2.. I'd suggest that there is a control(button) for only markers or layers from 4) point. For instance, if it's a marker, and the marker button is pressed, it will be able to place(and drag) the marker on the map.
5.. Need to substantiate the purpose.

**Comment by martyrion** [comment]
I am not sure I understood 100%. Tomorrow I will have an example ready and then we can discuss further on that. Have a nice day!

**Comment by martyrion** [comment]
Goodmorning! @Zemledelec I noticed that the 'ruler' tool creates 2 layers. Track and Corners. These layers shouldn't show up in the layer switcher, in my opinion, because they are 'helper' layers. 
- What do you think about that? How should they be exlcuded. Maybe add a layer option --> showInSwitcher : boolean?
- Could you add some comments to the RulerScene.js, exlaining the logic of the code? It would be very helpful for someone just starting to learn OpenGlobus - maybe even better outline the logic of OpenGlobus

thanks!
_Dimitris_

**Comment by Zemledelec** [comment]
You read my thoughts:) Would be handy with animation control too. I'd call it `_showInTheLayerSwitcher`

ok, I'll add the comments.

**Comment by martyrion** [comment]
This is the final concept I have in mind (inspired by Adobe Illustrator)

https://user-images.githubusercontent.com/63229987/185788045-1377d4ff-1e67-4c3e-a7c6-42709c760c11.mov



In order to do this we need:
- In layer a **_getEntityCollections & _getEntities**
- In Entity Collections a **_getEntities (it exists)**
- Maybe some other stuff also

This is what I meant by selecting which layer/collection you want to write into.
I think this creates a very nice interaction with the user.

... and of course in second stage editing entities, like this:

https://user-images.githubusercontent.com/63229987/185788254-40331113-aca2-411e-bd53-26072af3715c.mov


@Zemledelec

**Comment by Zemledelec** [comment]
It looks impressive, and more to say it could be very helpful if we have access to the vector data, such as billboards, labels, and geometry, so if we have it all, this is a way to implement style customization for the entities. 

P.S.
Also, it could lead to a great tool for map customization.

**Comment by martyrion** [comment]
That's what I also had in mind! A way for the user to create, edit and save all kinds of geospatial data, without the need to code (or at least with minimum coding).

I reckon it could be ready by the end of the year.

When I am talking about "saving' I mean a kind of persistent storage. Just saying...

**Comment by martyrion** [comment]
Hey @Zemledelec ,

can you add **setZIndex** and **getZIndex** for Vector layers? Is it difficult?

**Comment by Zemledelec** [comment]
It already exists.

**Comment by martyrion** [comment]
Thanks. What we have so far : 


https://user-images.githubusercontent.com/63229987/187032148-db4fcd02-190a-4ef2-b016-dee4926bc0a4.mov



**ISSUE**
Although the code changes the ZIndex of Vector point layer, it always remains on top. On the contrary it works with the Vector Layer "Countries".

Also, I didn't notice any difference with the ruler when ignoring terrain.

**Comment by Zemledelec** [comment]
Looks like a bug...I'll check. 

PS.
Dragging looks very cool!

**Comment by martyrion** [comment]
Hey @Zemledelec ,

Can you modify Planet.js and Globe.js so that the _**Globe**_ object has the option **_terrainAlternatives_**?
When we are creating the object we can pass an array of other terrains. This way I will be able to add terrain switcher functionality to the LayerSwitcher.

When we want to change terrain provider, we will just read from the **_terrainAlternatives_** and just run a setTerrain() to the desired terrain.

I tried to but didn't succeed.
Thanks!

**Comment by Zemledelec** [comment]
I'll make terrains as an array but the terrain is only one active. Replaced to https://github.com/openglobus/openglobus/issues/559

**Comment by Zemledelec** [comment]
@martyrion, have a little problem after merging:
![image](https://user-images.githubusercontent.com/5452251/187075568-54cff5a3-ffb8-4fea-ab9e-9821de813c9a.png)

Could you check it up, please?

**Comment by Zemledelec** [comment]
Also, ruler doesn't work.

![image](https://user-images.githubusercontent.com/5452251/187076276-ce53f4f4-c8b7-4c94-bcff-d75279a0efc2.png)

**Comment by martyrion** [comment]
I will in asap

**Comment by martyrion** [comment]
> @martyrion, have a little problem after merging:
> ![image](https://user-images.githubusercontent.com/5452251/187075568-54cff5a3-ffb8-4fea-ab9e-9821de813c9a.png)
> 
> Could you check it up, please?
> 

This is due to long names. I will make the dialog wider.

**Comment by Zemledelec** [comment]
Thanks, @martyrion!
I close the issue,  please read the text from https://github.com/openglobus/openglobus/blob/master/CONTRIBUTING.md
It will help support the code base in good condition, and free making small cleanups:)
