### ISSUE TITLE
Add LayerAnimation control timeout for layer loadend

### ISSUE THREAD

**Issue by Zemledelec** [openglobus/openglobus#558]
If it takes too long (loadend waiting) loading, then skip the layer.

**Comment by Zemledelec** [comment]
MR https://github.com/openglobus/openglobus/pull/562

FYI @yeluoyunfei

**Comment by Zemledelec** [comment]
MR https://github.com/openglobus/openglobus/pull/563

**Comment by Zemledelec** [comment]
@yeluoyunfei is it ok?

**Comment by yeluoyunfei** [comment]
> @yeluoyunfei is it ok?

Yes. Looks good.
