### ISSUE TITLE
GeoObject YAW, ROLL

### ISSUE THREAD

**Issue by martyrion** [openglobus/openglobus#564]
I noticed that when setting a geoObject's **YAW** to 0, modifying the provided example
https://github.com/openglobus/openglobus/blob/e61c6e503f2bb30ae83d9403338440adb963afc4/examples/geoObject/geoObject.js#L181

the object is not pointing to the north.

**Comment by Zemledelec** [comment]
@pavletto it's for you?

**Comment by pavletto** [comment]
Yep, thanks, I'm check that.

**Comment by martyrion** [comment]
I am not sure if it is related:

```javascript

        let myQuat = new Quat();
        console.log(myQuat); // Object { x: 0, y: 0, z: 0, w: 0 }
        myQuat.setFromEulerAngles(30,0,0) // pitch, roll, yaw
        console.log(myQuat); // Object { x: 0.25881904510252074, y: 0, z: 0, w: 0.9659258262890683 }
        let angles = myQuat.getEulerAngles();
        console.log(angles); //Object { roll: 0.5235987755982987, pitch: 0, yaw: 0 }

```
Is it normal for Quaternion to return roll when initially passed pitch?

**Comment by martyrion** [comment]
Also roll seems to be a bit off

![image](https://user-images.githubusercontent.com/63229987/188075884-bba8c0a0-e1c5-41bd-bb99-61673287a09d.png)

**Comment by pavletto** [comment]
Oh, you talk about plane model. Yaw and roll work fine - that model some bit broken. But I'll check it out later anyway

**Comment by martyrion** [comment]
> Oh, you talk about plane model. Yaw and roll work fine - that model some bit broken. But I'll check it out later anyway

Thanks, the same also happened with other models of the example.

**Comment by Zemledelec** [comment]
Hey @martyrion, I've just checked it up, and it works fine. Please take a look at `sandbox/airplane/airplane1.js` example you can run from the sandbox as well.

Cheers!

**Comment by Zemledelec** [comment]
...and update from the master! I've made a simple example.

**Comment by martyrion** [comment]
I can see the example with the yellow triangle showing correct yaw/roll, [https://github.com/openglobus/openglobus/blob/master/sandbox/airplane/airplane.html](url)

Still when using airplane.json file, yaw and roll are wrong - no big deal,  must be an issue of the 3d model itself!

Also I have tried to run sandbox/airplane/airplane1.html and I get this error in FireFox and Chrome:


![image](https://user-images.githubusercontent.com/63229987/188208008-f9068030-d18d-4b83-a92f-f25e3bcaaa23.png)

**Comment by Zemledelec** [comment]
Yes, it iw wrong model. Model must directed to -Z axis. Obviously plane example models directed..somehow. You can use any model you want.

Does ruler control works fine?

**Comment by Zemledelec** [comment]
...try set instancing : false and set tag: "plane2" for second entity.

**Comment by Zemledelec** [comment]
...and update the master branch. "No live reload" log anymore here. Try to clean the browser cache.

**Comment by pavletto** [comment]
> I can see the example with the yellow triangle showing correct yaw/roll, [https://github.com/openglobus/openglobus/blob/master/sandbox/airplane/airplane.html](https://github.com/openglobus/openglobus/issues/url)
> 
> Still when using airplane.json file, yaw and roll are wrong - no big deal, must be an issue of the 3d model itself!
> 
> Also I have tried to run sandbox/airplane/airplane1.html and I get this error in FireFox and Chrome:

yep. this is what i meant - model is broken. it has incorrect initial states. it's my first try of import model from blender to openglobus :smile:

**Comment by martyrion** [comment]
Thanks guys!
