### ISSUE TITLE
GeoVideo example not working

### ISSUE THREAD

**Issue by genert** [openglobus/openglobus#569]
The example with GeoVideo does not work. Neither the Las Vegas or the precipitation video plays - http://openglobus.org/examples/geoVideo/geoVideo.html

This might be related:
<img width="599" alt="Screenshot 2022-09-08 at 12 47 11" src="https://user-images.githubusercontent.com/1218788/189103558-a937fa14-2011-4515-9b82-18dc1bbd9c51.png">

**Comment by Zemledelec** [comment]
HI @genert , what OS and browser?

**Comment by Zemledelec** [comment]
@genert check the last master please. This is texImage2D issue.
