### ISSUE TITLE
LayerSwitcher list do not refresh when layer add/remove event happen

### ISSUE THREAD

**Issue by Zemledelec** [openglobus/openglobus#575]
FYI @martyrion

**Comment by martyrion** [comment]
Hey @Zemledelec! I am looking into it. Are you sure, that adding a layer doesn't work? In the layerSwitcher.html, I think it works.

**Comment by yeluoyunfei** [comment]
@martyrion you can try add/remove layer after control is created.  also, previously, control can be created in globe constructor, now it has issue if doing so.

**Comment by yeluoyunfei** [comment]
Also, there is no scroller now

**Comment by Zemledelec** [comment]
Fixed remove/add baseLayers only.
