### ISSUE TITLE
question: how frequently is the npm package updated?

### ISSUE THREAD

**Issue by samvanemelen** [openglobus/openglobus#582]
Hi

I'm super excited to start building project with openglobus {and even contribute if I am able). But for I project I am playing with right now I needed a feature that is in the 0.13.10 version (LayerAnimation). I saw that npm is only up to date until 0.13.8. Is this updated automatically every few months, or is this done manually? Or do you advise to use the repository as source rather than npm?

Thanks in advance

**Comment by pavletto** [comment]
Hi @samvanemelen. Npm package will be updated automatically when creating a release in project. Maybe something went be wrong, I'll check it. Thanks.

**Comment by pavletto** [comment]
@samvanemelen new release is ready and published to npm!

**Comment by Zemledelec** [comment]
Hi @samvanemelen, and welcome! Ask any questions in the issues or forum. Cheers!

**Comment by samvanemelen** [comment]
Seems to have published perfectly, thanks!
