### ISSUE TITLE
Suggestion to make activation height for Sun variable

### ISSUE THREAD

**Issue by samvanemelen** [openglobus/openglobus#584]
I am working on a project where I want to keep the day/night cycle, even when zoomed in. I saw this is controlled by a global variable 'activation height'. It should only be a small change to the implementation by adding to the Sun Class:
`this.activationHeight = options.activationHeight || 12079000.0;`
and changing:
` if (cam.getHeight() < ACTIVATION_HEIGHT || !this._active) {`
to
` if (cam.getHeight() < this.activationHeight || !this._active) {`

Not entirely sure yet how to do the issue / pull request cycle but this is already a start 😉

**Comment by pavletto** [comment]
I think it's a good idea. Try to create PR! We are check them.

**Comment by samvanemelen** [comment]
Great! If I understand correctly, I fork the repo, make a branch named feature/584_something and make a pull request with that branch?

**Comment by pavletto** [comment]
Yep!

**Comment by yeluoyunfei** [comment]
@samvanemelen , I think this is done already?
