### ISSUE TITLE
Suggestion to make use of the GitHub Discussion feature

### ISSUE THREAD

**Issue by samvanemelen** [openglobus/openglobus#585]
Is there a reason why the repository does not make use of the [Github Discussion Feature](https://docs.github.com/en/discussions) but uses the google group as forum? I feel that a discussion/forum feature directly in the repository might be a more integrated way to discuss performance, features, just plain questions etc.

**Comment by pavletto** [comment]
And another good idea. I thought about it before. We can try Discussions instead gitter, but until we give up the forum - let's see if  Discussions will be more popular than the forum
