### ISSUE TITLE
Geometry which extends from base to a certain height

### ISSUE THREAD

**Issue by ns-pyadav** [openglobus/openglobus#602]
Is It Possible to create a Geometrical Shape which extends from the ground to a certain altitude. Something like [this](https://globe.gl/example/world-population/)

**Comment by Zemledelec** [comment]
Hi @ns-pyadav, check it out:
http://openglobus.org/examples/rays/rays.html
http://openglobus.org/examples/polylines/polylines.html
https://openglobus.org/examples/polylines/polylines2.html

**Comment by ns-pyadav** [comment]
Hi @Zemledelec , Thank for the help !!
