### ISSUE TITLE
WMS.js setting layers property problem

### ISSUE THREAD

**Issue by busatoa** [openglobus/openglobus#607]
Hi,
in the WMS.js at

"this.layers = options.layers"

Uncaught TypeError: setting getter-only property "layers"

have yopu any idea to overcome this?

Regards,
Alessandro

**Comment by busatoa** [comment]
I tested locally this solution:

I've modified WMS.js constructor

this._layers = options.layers;

because "_layers" is defined in Layers.js as array variable 

and the layers will be passed as array

example:
var sdlsNavigations = new WMS("Natural Earth", {
            visibility: true,
            isBaseLayer: false,
            url: 'https://sdls.ogs.trieste.it/geoserver',
            layers: ['sdls:AllNavigations'],
            version: '1.1.1',
            opacity: 1.0,
            specular: [0.001, 0.00046, 0.0003],
            shininess: 15,
            ambient: [0.1, 0.1, 0.2],
        });

If it is ok you could update the code into the repository.

Thanks,
Alessandro

**Comment by Zemledelec** [comment]
Hey @busatoa , thank you! It was another bug inside Layer, somehow `_layers` has merged in the class. I removed it from the base layer. WMS is good now with public `this.layer`.
