### ISSUE TITLE
WMS.js request for new feature, pass to url extra (vendors) parameters 

### ISSUE THREAD

**Issue by busatoa** [openglobus/openglobus#609]
I need to pass extra parameters into URL which are not included into default WMS.js options, both by standard wms reference or by vendors, ie. SLD  or TRANSPARENT;
Transparent option is very important for my job, it permits me to get small rendered layer from geoserver without cover the rest of globe.

I locally solved in this way,
```
var sdls = new WMS("Natural Earth", {
[...]        },**{     
                TRANSPARENT:true,
                SLD:'http://localhost/cache/sld/AllNavigations.xml'
        }**);
```

I add into WMS constructor a third parameter with extra  options.

In WMS.js constructor:
```
 constructor(name, options,extra ) {
        super(name, options);
        **this.extra = new URLSearchParams(extra).toString();**
  [...]
}

//  URLSearchParams return a query string from map

  static createRequestUrl(
        url,
        layers,
        format = "image/png",
        version = "1.1.1",
        request = "GetMap",
        srs,
        bbox,
        width = 256,
        height = 256,
        **extra**

    ) {
        return `${url}/wms?LAYERS=${layers}&FORMAT=${format}&SERVICE=WMS&VERSION=${version}&REQUEST=${request}
        &SRS=${srs}&BBOX=${bbox}&WIDTH=${width}&HEIGHT=${height}&` + extra;
    }

 _createUrl(segment) {
        return WMS.createRequestUrl(
            this.url,
            this.layers,
            "image/png",
            this._version,
            "GetMap",
            this.srid?this.srid:segment._projection.code,
            this._getBbox(segment.getExtent()),
            this.imageWidth,
            this.imageHeight,
            **this.extra**
        );
```

I know this way will not match your code architecture or style, it's just a way 
to show the feature I need.

Thanks a lot,
Alessandro

**Comment by Zemledelec** [comment]
It's ok! Could you make a pull request, please?

**Comment by busatoa** [comment]
ok, it's a bit offtopic  but before creating pull request I have to push a branch but 

remote: Permission to openglobus/openglobus.git denied to busatoa.
fatal: unable to access 'https://github.com/openglobus/openglobus.git/': The requested URL returned error: 403

I used a personal token to clone etc. and to push

Any tip?

Thanks.

**Comment by busatoa** [comment]
I created a pull request via fork because I think I haven't got permission to push new branch  under openglobus master.

**Comment by Zemledelec** [comment]
@busatoa done?:)
