### ISSUE TITLE
Area selection to get an extent to use in remote OGC services like WFS

### ISSUE THREAD

**Issue by busatoa** [openglobus/openglobus#611]
I need to select an area (extent) in order to query WFS service,
so I implemented a control named **Selection** based on **Ruler** and **GeoImageDraggingControl** (for activation button)
you can check all on  **fork busatoa:feature/add_selection_control**
The example code is this:

```
new Selection({
        ignoreTerrain: false,
        autoSelectionHide:true,  //used for clear rectangle after passing extent to callback
        onSelect: (extent) => {
            var vectorSource = new ol.source.Vector({
                format: new GeoJSON(),
                url: function (extent) {
                    return 'https://snap.ogs.trieste.it/geoserver/snap/ows?service=WFS&' +
                            'version=1.1.0&request=GetFeature&typename=snap:all_dataset_segy_view&' +
                            'outputFormat=application/json&srsname=EPSG:4326&' +
                            'bbox=' + extent.join(',') + ',EPSG:4326';
                },
                strategy: function (extent, resolution) {
                    if (this.resolution && this.resolution != resolution) {
                        this.loadedExtentsRtree_.clear();
                    }
                    return [extent];
                }
            });
            vectorSource.loadFeatures(extent);
            console.log(extent);
        }
    });
```

The control is activate via button , the activation stop main mouse navigation (pan) and the rectangle is 
drawn by "left mouse down + mouse move".

The icon button is missing in the sense I'm using the GeoImageDraggingControl icon because at the moment
I don't know how to create new one (any suggestion?)

I modified UIHelpers
`export function btnClickHandler(btn_id, dialog_id, dialog_selector, btn_icon_id, callback) `

I add callback parameter to send the button status in order to deactivate or activate mouse navigation
I know this solution is due to my leak of knoledge about openglobus architecture.

if it is not implemented yet I hope it could be usefull , any suggestion ?

Regards,
Alessandro

**Comment by Zemledelec** [comment]
Hey! I've just tried, I see console.log but nothing happens on the map. I suppose we have to see a poly or outline on the map, therefore I recommend using isClosed: true option for polyline, and just append a point to the end of the polyline, then draw Vector area, but not it's not necessary the first time.

**Comment by Zemledelec** [comment]
@busatoa , could you show a picture of what to see? Also, I removed all openlayers strategy code, and only console.log was left.

**Comment by busatoa** [comment]
<img width="484" alt="Screenshot 2022-11-29 at 17 14 11" src="https://user-images.githubusercontent.com/85111824/204783976-43201d5a-d01c-4527-ba5c-13fe2353bfcc.png">

After selection a callback is called and into this function you implement the logic of you application using properly the extent, for example simply console.log, query WMS service or other ones.

**Comment by Zemledelec** [comment]
I see! Cool! It works! For the beginning very cool, and could be as a view selection tool the same as ol do. For areas, polygons sounds better. 
@busatoa make merge request, please!

**Comment by Zemledelec** [comment]
...but not the same button for images.

**Comment by busatoa** [comment]
@Zemledelec have you designed the image button by yourself or you are using a web icon repository?

**Comment by Zemledelec** [comment]
This button @martyrion. Do you want to find a proper icon repository for buttons?

**Comment by busatoa** [comment]
I'm using in my webapp icons by https://icons.getbootstrap.com
I could try to use an icon (I saw one which is called bbox) in selection control, if you
agree or I can wait for new icon by @martyrion (or others) in order to keep the coherent graphical design with 
the rest of openglobus. what do you think?

**Comment by Zemledelec** [comment]
I think it's good. 

I'm not sure how to make it right, but if it's possible to keep icons inside the control folder, I assume that in the future all controls would be replaced in a separate repository, such as "openglobus plugins" or something, the same as examples and sandbox.

FYI @openglobus/openglobus-team

**Comment by busatoa** [comment]
Ok, I updated the branch,
I've add new field activationIconClasses:
activationIconClasses: ['bi', 'bi-bounding-box-circles']
if activationIconClasses is defined it shows:
<img width="130" alt="Screenshot 2022-12-01 at 11 00 43" src="https://user-images.githubusercontent.com/85111824/205026779-d5022b9e-0a1d-4e31-be52-0e42d5ba3c21.png">
otherwise I implemented a simple custom icon based on "span" and its border
<img width="104" alt="Screenshot 2022-12-01 at 11 00 01" src="https://user-images.githubusercontent.com/85111824/205026951-afc627fb-71c3-46cf-9cac-ea3312d5f8fc.png">
just not to touch the main css I preferred, for the moment, to hard set position of the button  copying the one of geo-image-dragging; this position or other aspects of button could be passed as options (implementing a library default value in case of undefined items) in order to make the application developer free to adapt it to its application design.

In order to use bootstrap-icons in the example you should include:
\<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.2/font/bootstrap-icons.css">

if it's ok I could create a pull request.

**Comment by Zemledelec** [comment]
I think it's good. But, for the future we would need some HTML control layouts, the same way leaflet or ol do, and we could just add buttons in a container.
Frankly speaking, I don't like external url for icon set, I suggest placing bare svg icon code into the control html template, what do you think @busatoa?

**Comment by busatoa** [comment]
you are right about external url because in this way the code totally depends on hope which remote server  be up and running 24H7. the better solution in production  is , via npm or direct download , to use bootstrap-icons (or other libraries) locally.

**Comment by busatoa** [comment]
I created new pull request it failed on docs step, I followed the same steps for WMS, have you any suggestion for this?

**Comment by Zemledelec** [comment]
Merged!
