### ISSUE TITLE
Adding 3D models to map

### ISSUE THREAD

**Issue by GurgenMelqonyan** [openglobus/openglobus#615]
Seems there's no feature to add some 3D model as icon to map. Will be thankful to get some example if I'm wrong and there IS such feature

**Comment by pavletto** [comment]
You can add 3d models use [geo objects](https://openglobus.org/examples/geoObject/geoObject.html)

**Comment by pavletto** [comment]
sorry somthing wrong with examples( you can watch how it's work localy now

**Comment by GurgenMelqonyan** [comment]
Thanks a lot.

**Comment by Zemledelec** [comment]
GeoObjects are very simple 3d objects, but for most purposes, it's enough. Especially, it's instanced, and you can have a lot of them on the map.

Hey @pavletto, I considered that we need a tutorial on how to export simple meshes into 3d geoObject. What do you think? :)
