### ISSUE TITLE
Vector layer 'lclick' does not give clicked entity as pickingObject

### ISSUE THREAD

**Issue by samvanemelen** [openglobus/openglobus#626]
I have a Vector layer with many points. When a point is clicked I want to get the information of the clicked entity (point). But the 'lclick' event does not return the entity as pickingObject attribute of the event. In the pickingObject attribute I find the basemap below. Is this expected behaviour? I would expect this event to return the clicked object instead.

Here is a codepen of the issue: https://codepen.io/samvanemelen/pen/WNKyopq

**Comment by Zemledelec** [comment]
Hi, Sam! event.pickingObject is a pointer to a picked object, and consol.log reset the pointer when happen other events, for instance, `lup`(left mouse up). You have to use it like this  `layer.events.on('lclick', e => console.log(e.pickingObject))`. Cheers!))

P.S.
Reasonable question, why is the baslelayer in the pickingObject thow, I suppose in the pickingObject you have always something from the picking objects handler, which always looking for a what to pick.

**Comment by samvanemelen** [comment]
I can't believe I didn't bother to try that out, but that is indeed what happens. I would however expect it to remain on the entity even after a 'lup' event. But probably there is a mouse move event that sets it to the baselayer or something like that.

Thanks for straightening this out!
