### ISSUE TITLE
Ruler and Selection missing start/stop entity corners

### ISSUE THREAD

**Issue by busatoa** [openglobus/openglobus#627]
Hi,
I synchonized the openglobus sources  with the last changes in git,
in to the Ruler (and Selection which is based on Ruler sources) the entitty corners aren't displayed no more.

<img width="491" alt="Screenshot 2023-02-03 at 08 02 41" src="https://user-images.githubusercontent.com/85111824/216534690-5920eb3e-746c-454c-a3dd-01faf924ca8c.png">

Any idea, suggestion? 
Thanks a lot.
Alessandro

**Comment by Zemledelec** [comment]
Hi @busatoa, is this the master branch?

**Comment by busatoa** [comment]
I'm working with my fork busatoa/openglobus which is synchronized and updated with  openglobus/openglobus:master.

**Comment by pavletto** [comment]
Hi @busatoa. I think this problem may be related to geoobjects. But in current master I see correctly working Ruller. Can we check your fork?

**Comment by busatoa** [comment]
Hi,
the version of GeoObject.js is Jan 26, 2023, 1:17:57 PM	06e28c5	Pavel Sukhodolski	remove radians from go
I cleaned and rebuilt it but nothing.
I tried to view the openglobus example of rulerr using local webserver with no result.
(I tried to revert the file to previous versions but the ruler keeps the same problem)

**Comment by busatoa** [comment]
just to drop any doubt I cloned directetly the master , rebuilt the lib, and executed the ruler example,
but the problem persists.

**Comment by pavletto** [comment]
Can you check `/examples/ruler/ruler.html` example on your repository? unfortunately I can't replay same issue

**Comment by busatoa** [comment]
the ruler.html version is Aug 1, 2022, 11:08:31 AM	755e5df	Zemledelec	Added ruler example

**Comment by pavletto** [comment]
no. I mean is it example works correctly? do you see corners in it?

**Comment by busatoa** [comment]
sorry,
no it doesn't work,next step to be very sure
I used another linux host
git clone https://github.com/openglobus/openglobus.git
python -m SimpleHTTPServer 9900
running tthe ruler.html there the corners also don't appear

**Comment by Zemledelec** [comment]
thinking...

**Comment by Zemledelec** [comment]
@busatoa could you check the last master, please? I've remade scaleByDistance parameter in the ruler controller.

**Comment by busatoa** [comment]
the problem persists,
git pull 
 sandbox/geoObject/cube.json        | 14 ++++++
 sandbox/geoObject/geoObject.js     | 98 ++++++++++++++++++++++++++++++++++++++
 sandbox/geoObject/index.html       | 14 ++++++
 src/og/control/ruler/RulerScene.js | 19 ++------
 src/og/entity/GeoObject.js         |  4 +-
 src/og/shaders/geoObject.js        | 80 +++++++++++++++++++++----------
 6 files changed, 185 insertions(+), 44 deletions(-)

I executed ruler.html example (the same behaviour with Firefox and Chrome)
<img width="344" alt="Screenshot 2023-02-06 at 14 00 00" src="https://user-images.githubusercontent.com/85111824/216978276-f677a568-8d38-47c4-bb8d-6d9ec67cff89.png">

**Comment by busatoa** [comment]
Ok, I download the previous versions using the tags,
I tested that openglobus-0.14.4  and below one works.

**Comment by busatoa** [comment]
I compared the master with the 0.14.4 release and the problem was introduced with "og/entity/GeoObjectHandler.js", I copied the file by 0.14.4 and the problem disappeared
I hope it could be usefull.

**Comment by pavletto** [comment]
Are you have problems on Firefox, right? I reproduce issues and detect source of problem. Tomorrow I'm fix this.

**Comment by busatoa** [comment]
That's fine! In the meanwhile I prepare the update of selection control to use the new very nice Vector layer feature "scaleByDistance" as you have done in RulerScene. Thanks.

**Comment by pavletto** [comment]
Done! @busatoa, please check issues on latest master

**Comment by busatoa** [comment]
<img width="490" alt="Screenshot 2023-02-07 at 12 38 32" src="https://user-images.githubusercontent.com/85111824/217235029-1af5999e-64da-4e5f-9475-9dcf229419c2.png">
@pavletto , it works now, thank you very much.

**Comment by pavletto** [comment]
Great! I'm close this issue. Thanks for reporting

**Comment by pavletto** [comment]
So, @busatoa  what are you doing? if it not a secret of couse). looks very interesting

**Comment by busatoa** [comment]
I'm a developer in a research institute (https://www.ogs.it),
we have got  a catalog of datasets of seismic sections and multibeam acquired by us and other partners moreover  in the mediterranean sea and in antarctic zone; at the moment the datasets are made available through two different 2D application due to different projection and the available library years ago, the old 2D version (https://snap.ogs.trieste.it and https://sdls.ogs.trieste.it). the lines that  you have seen into the screenshots are the tracks of vessel during the dataset acquisition. The first step is merging the  two maps (with different projection)  together with no projection troubles presenting catalog into the globe, in particular your globe which is very nice. I'd like to add a reference to your project in my app, have you any logo for the powered-by?
