### ISSUE TITLE
User interaction performance track: able to fire event with fps info (frame rate) for user interaction (pan, zoom, user interaction etc.)

### ISSUE THREAD

**Issue by bow0110** [openglobus/openglobus#632]
To track user interaction performance. Map web app may want to log fps during user interactions, like zoom, pan, etc. Does openglobus already or should have this feature to listen to moveend event and get fps number during the animation?

**Comment by pavletto** [comment]
If I remember correct we have something in 'DebugInfo'. @Zemledelec help) Also you can use standard fps rate tool in devtools

**Comment by Zemledelec** [comment]
Hi @bow0110 ! You could try DebugInfo() control (from control folder), for example `globus.planet.addControl(new DebugInfo())` there are a few parameters such as deltaTime(time of a frame rendering)/FPS etc.

**Comment by Zemledelec** [comment]
...also you can get fps from `globus.renderer.handler.deltaTime`

**Comment by Zemledelec** [comment]
...the camera has moveend event, mouse also has moveend event:)
