### ISSUE TITLE
Using Wavefront obj

### ISSUE THREAD

**Issue by GuittonHubert** [openglobus/openglobus#638]
Hi @Zemledelec,

Thank you for the work you've accomplished. I really appreciate!
As mentioned in #615 and referring to [geoObject.js](https://github.com/openglobus/openglobus/blob/master/sandbox/geoObject/geoObject.js) I know and was able to display a mesh object. 

Currently, I'm trying to display without any success a obj file [Boeing 787-9 Dreamliner](https://free3d.com/3d-model/el-al-boeing-787-9-dreamliner-406117.html) and I can't figure out. Based on the sandbox code, I tried two different COTS to parse my model and get the normals, vertices and texture coordinates:
  - https://www.npmjs.com/package/wavefront-obj-parser using returned vertexNormals, vertexPositions and vertexUVs
  - https://www.npmjs.com/package/obj-file-parser using returned vertexNormals, vertices and textureCoords
All those fail...
Could you please help me to go through? Thank you very much.

Hubert

**Comment by Zemledelec** [comment]
Hi Hubert!
Since the #615 GeoObject constructor has changed, and now you need to instantiate Object3d and use it in GeoObject constructor, like this:

./Object3d.js
```
    let plane3d = new Object3d({
        vertices: [2, 5.5, -1.3, 21, 6, -3, 21, 6, -8, .... ],
        normals: [...],
        indices: [0,2,1,0,3,5, ...],
        texCoords: [...],
        ....
    });
```

```
    let entity = new Entity({
        lonlat: [1, i, 20],
        name: "b737",
        geoObject: {
            pitch: 0,
            yaw: 0,
            roll: 0,
            scale: 1.0,
            instanced: true,
            tag: "plane",
            color: "red",
            object3d: myPlane
        }
    });
```

And then, insert the entity into EntityCollection or Vector layer.

P.S.
If it doesn't work, please share your vertices, indices, etc.

**Comment by GuittonHubert** [comment]
Hello,

I coded as you mentioned in your previous post and I do not have the expected result. Please find the JSON file I use (I renamed into .txt to be able to attach the file) and the properties I use to create the Object3d:

[El Al 787-9.txt](https://github.com/openglobus/openglobus/files/10897844/El.Al.787-9.txt)



```
  var parseWFObj = require('wavefront-obj-parser');
  ...

  let geoObjects = new og.EntityCollection({
      entities: [],
      scaleByDistance: [100000, 4000000, 10000.0]
  });
  ...

  const model = parseWFObj(data);

  let obj3d = new og.Object3d({
      center: true,
      vertices: model.vertexPositions,
      normals: model.vertexNormals,
      indices: model.vertexPositionIndices,
  });

  let entity = new og.Entity({
      lonlat: [103, 1, 8000],
      name: "obj-0",
      geoObject: {
          pitch: 0,
          yaw: 0,
          roll: 0,
          scale: 1.0,
          instanced: true,
          tag: 'plane',
          color: 'red',
          object3d: obj3d
      }
  });

  geoObjects.addEntities([entity]);
  geoObjects.addTo(globus.planet);
```


Data come from [Boeing 787-9 Dreamliner](https://free3d.com/3d-model/el-al-boeing-787-9-dreamliner-406117.html). Hope this helps

**Comment by Zemledelec** [comment]
Wrong  `scaleByDistance: [100000, 4000000, 10000.0]`.
Use `scaleByDistance: [MAX32, MAX32, 1.0]` - for scale 1:1, where MAX32=2147483647, 
or try `scaleByDistance: [100, 4000000, 1.0]`, where 100 is a distance (m) from 0 to 100 m you see an object with 1:1, since 100m the object will be the same size as you see it from 100 m, and 4000000 is the distance since the scaled object will be scaled the same way as 1:1, but from the point of view of 100 m scale)) The third value is just a scale, set it to 1.0. Just try different values for the object.
Also, Object3d doesn't support normal and vertices separate indices arrays, so you have to export obj with one set of indices both for vertices and normals.

**Comment by GuittonHubert** [comment]
Hello @Zemledelec 

Thank you for your explanations, this is far more clear now. I used your second proposal for the scaleByDistance, and now I have the following errors in the Javascript console:
`
[Error] WebGL: INVALID_VALUE: uniform3fv: invalid size
	uniform3fv
	_displayPASS (bundle.js:90882)
	draw (bundle.js:91065)
	_drawEntityCollections (bundle.js:111149)
	draw (bundle.js:111227)
	(fonction anonyme) (bundle.js:110918)
	drawFrame (bundle.js:130960)
	(fonction anonyme) (bundle.js:131008)
[Error] WebGL: INVALID_VALUE: uniform3fv: invalid size
	uniform3fv
	_pickingPASS (bundle.js:90944)
	drawPicking (bundle.js:90931)
	drawPickingEntityCollections (bundle.js:114878)
	_entityCollectionPickingCallback (bundle.js:114925)
	_drawPickingBuffer (bundle.js:111320)
	draw (bundle.js:111229)
	(fonction anonyme) (bundle.js:110918)
	drawFrame (bundle.js:130960)
	(fonction anonyme) (bundle.js:131008)
`

I understand that is is related to the array of indices for normals and vertices that differ. Unfortunately, I'm not a 3D modeling expert and I cannot fix it. Do you have a toolchain to produce Object3d or do you know any resource web site for models? Thank you for your help.

**Comment by GuittonHubert** [comment]
I realized there is a blender.py script in the repository to turn a model into a structure for Object3d.

So, I used blender to transform all the faces of my model into triangles, then using the script the resulting json file was compatible. However nothing is displayed, even when tuning the aforementioned 'scaleByDistance' option.

I think my model is overly complex, and it's too complicated to investigate right now.

**Comment by Zemledelec** [comment]
Your model Is fine, I saw it, but it has separate index arrays...I'll check how to use blender to export the correct indices, and answer.

**Comment by Zemledelec** [comment]
Btw, wavefront-obj-parser reads separate indices for faces, but in webgl(opengl etc) we need only one indices array! 

  // These come from the `f` face lines
  vertexNormalIndices: [...],
  vertexUVIndices: [...],
  vertexPositionIndices: [...]

...and I think here it is, https://github.com/chinedufn/expand-vertex-data need to check.

**Comment by GuittonHubert** [comment]
Hi,

I gave a try to [expand-vertex-data](https://github.com/chinedufn/expand-vertex-datal) as suggested and this was a huge step forward! Hereafter is a screenshot of the rendered model:
![image](https://user-images.githubusercontent.com/61505725/224335667-a089ee08-558e-417e-860a-839bb4dffbb2.png)

I worked with blender to remove orphaned blocks, converted all faces into triangles and loaded the given model into openglobus directly.

```
           const model = parseWFObj(data);

            // Pass this data into your ELEMENT_ARRAY_BUFFER and ARRAY_BUFFERS
            var expandedModel = expandVertexData(model, { facesToTriangles: true });

            let obj3d = new og.Object3d({
                center: true,
                vertices: expandedModel.positions,
                normals: expandedModel.normals,
                texCoords: model.uvs,
                indices: expandedModel.positionIndices,
            });
```

**Comment by Zemledelec** [comment]
It looks like insufficient index bit depth. I've made a fix, check the last master, please.

**Comment by GuittonHubert** [comment]
Good morning @Zemledelec. Thank you very much for keeping on working on this topic. I tried your fix and the result is exciting! Please find here a screenshot:
<img width="804" alt="Capture d’écran 2023-03-11 à 09 42 40" src="https://user-images.githubusercontent.com/61505725/224474592-af4ba0cc-a378-43e6-bc2c-4e60baa8180b.png">

The related code is below:  
```
let geoObjects = new og.EntityCollection({
        entities: [],
        scaleByDistance: [10, og.math.MAX32, 0.1]
    });

  // Pass this data into your ELEMENT_ARRAY_BUFFER and ARRAY_BUFFERS
  const model = parseWFObj(data);
  const expandedModel = expandVertexData(model, { facesToTriangles: true });

  let obj3d = new og.Object3d({
      center: true,
      vertices: expandedModel.positions,
      normals: expandedModel.normals,
      indices: expandedModel.positionIndices,
  });

  let entity = new og.Entity({
      lonlat: [0, 0, 8000000],
      name: 'airplane',
      geoObject: {
          pitch: 0,
          yaw: 0,
          roll: 0,
          scale: 1.0,
          instanced: true,
          tag: 'plane',
          color: 'red',
          object3d: obj3d
      }
  });

  geoObjects.addEntities([entity]);
```

I notice however that the altitude passed in the lonlat or altitude properties  of the entity has no effect on the position of the model; am I wrong? Do I need to make a transformation to change it? All your comments are welcome.

Have a nice day

**Comment by Zemledelec** [comment]
It should work. I’ll check.

**Comment by Zemledelec** [comment]
I've just checked, and it works fine. Take a look into sandbox/geoObject example.

**Comment by GuittonHubert** [comment]
Ok, it works indeed; from my experience the value for the altitude is thightly coupled to the scaleByDistance, scale factors. So I had to tune those and made it work:

<img width="804" alt="Capture d’écran 2023-03-12 à 18 47 00" src="https://user-images.githubusercontent.com/61505725/224562791-b11dc59e-a805-442c-9722-8ef7fe4873e6.png">

However, the rendering is not always correct (please see below), maybe due to a z-index ordering, I suppose:

<img width="412" alt="Capture d’écran 2023-03-12 à 18 49 50" src="https://user-images.githubusercontent.com/61505725/224562914-c6213ab5-b81d-41b7-a401-e41d55d9cbdc.png">

I read in #561 that @Zemledelec is not in favor of adding a zIndex property right now since it implies to change the source code with potential side-effects. At the moment, is there a way to prevent the map tiles from overlapping the geoObject?

Thank you for your suggestions.

**Comment by GuittonHubert** [comment]
Hello @Zemledelec,

I think we can close this issue, since the rendering of the model is more generally linked to GeoObject, in my opinion. So I propose to close it, and probably open a new issue. 

Whatever, I would like to thank you for your reactivity and great help! This is a huge step for me! I really like your project and it deserves to be known.

**Comment by Zemledelec** [comment]
Hey @GuittonHubert , thank you! Agree. Let's close the issue, about your question, wings disappear because, they are really under ground, but the ground from the distance always low resolution, and it means that in real scale elevation in the point is 1000m but in low resolution, it's 1500m, because neighbour points 1700m and 1400m for instance. In this case we use zOffset parameter on distances but near the ground it's 0.  You could try changing polygonOffsetUnits parameter of a Vector layer, set it -10000, or 10000 more or less. Cheers! Welcome with any questions, and more issues!
