### ISSUE TITLE
How to convert DEM in GeoTIFF to Openglobus ddm tiles?

### ISSUE THREAD

**Issue by trolleway** [openglobus/openglobus#64]
Is there a some command-line tools for that?

There is a new use-case for operate custom DEM: an DJI drone and Agisoft Photoscan software can produce a high-detail DEM and ortophoto imagery. There is a not current tool for easy create a 3d webmap with custom DEM for big area. 
I tired CesiumJS, they also still not have converter from DEM to own terrain tiles.

**Comment by Zemledelec** [comment]
Globus doesn't have special tool for various elevation sets. There is only tool that makes .ddm(height grid) from .hgt (format) files.
I have never thought about it, I have been thinking about google earth, esri, cesium elevation data, that could be used as custom terrain provider with globus api. I suppose that guys have nice elevation data at all.
If you explain the data you have(some example file), I will see what I can do.

P.S.
Frankly speaking, I think about convenient hi-res elevation data set, like LIDAR etc,  but find nothing yet.

**Comment by trolleway** [comment]
Here is a real-world examples: 
https://yadi.sk/i/altUs9yj3UXGYG
https://yadi.sk/i/8dVKztSN3UXH76
DEM created from 20 flights at DJI Phantom 4 with Agisoft Phtotoscan. Files can be inspected in QGIS.
It shows much more details of hills than google earth data. 
![8](https://user-images.githubusercontent.com/4630662/38928454-8fc72054-4311-11e8-9914-6954537e213f.png) http://trolleway.nextgis.com/resource/2119/display


I try to make 3D visualisation in browser like this https://sketchfab.com/models/ce19a2c100814b1eaad36e89f8d88d21, but for much more area and in some leaflet-like viewer.

**Comment by Zemledelec** [comment]
Quite the same https://github.com/openglobus/openglobus/issues/99 i'm working on.

**Comment by Zemledelec** [comment]
Replaced to [geotiff example issue](https://github.com/openglobus/openglobus/issues/229)
