### ISSUE TITLE
the globus canvas rendering freeze during window resize

### ISSUE THREAD

**Issue by busatoa** [openglobus/openglobus#642]
Hi,
the globus canvas rendering freeze during window resize when its dimensions , width or height, drop to 0 for a while.

at the moment I used a simple workaround to solve it, I've include this piece of code to the page

window.addEventListener('resize', () => {
         globus.renderer.start()
 });
(I used Firefox)
<img width="128" alt="Screenshot 2023-03-08 at 13 45 04" src="https://user-images.githubusercontent.com/85111824/223718049-d81325ac-f3e8-4b8c-a6ff-ea37bf66e0a7.png">
<img width="128" alt="Screenshot 2023-03-08 at 13 45 15" src="https://user-images.githubusercontent.com/85111824/223718058-979cc554-1810-4117-831c-f0550d2f0aad.png">
<img width="160" alt="Screenshot 2023-03-08 at 13 45 28" src="https://user-images.githubusercontent.com/85111824/223718061-f3bed3cb-712c-47c7-8f92-b2bedd11df81.png">

Alessandro

**Comment by Zemledelec** [comment]
Resizing is a heavy operation. if the size (or display none, or invisible) is zero it stops working, it's fine. When resizing, canvas decreases its resolution, but it's fine. All mechanics inside the renderer resize see ONCANVASRESIZE in renderer, and drawFrame in Handler.

**Comment by busatoa** [comment]
at the time of reducing browser window  size(I test both Firefox and Chome) canvas size is reduced until "0" size, then, widening the window again the canvas seems not intercept the "resize" event to drawFrame again; if you put the browser window  below other application or simply hiding the current table opening a new one for a while the canvas rendering come back; I think that is a drawback  due to a perfomance mechanism adopted by the browser to save resources (battery and so on) consumed by the GPU when the window is not visibile.
have you reproduced the problem by your browser?

**Comment by Zemledelec** [comment]
It's easy to check. Set breakpoint into _toggleVisibilityChange in the Handler.js, and start and stop methods. Check https://github.com/openglobus/openglobus/pull/648 MR please.

**Comment by Zemledelec** [comment]
...or better way is using System Monitor, htop or similar

**Comment by Zemledelec** [comment]
MR https://github.com/openglobus/openglobus/pull/648

**Comment by pavletto** [comment]
@Zemledelec I confirm this issue. Catched it sometime but don't cracked replay mechanism. I'll try to reproduce and fix it

**Comment by Zemledelec** [comment]
Merged! @busatoa could you check, please:)

**Comment by busatoa** [comment]
Fine, it works!

Thank you.
