### ISSUE TITLE
GeoImage glitches when size is small

### ISSUE THREAD

**Issue by program-sam** [openglobus/openglobus#646]
When the dimensions of a GeoImage are small (less than 0.01 degree or so), the image glitches until the edge of the current tile it seems.

https://user-images.githubusercontent.com/75586344/224081343-f93bef56-0c18-4f43-9a1e-7a63e3095f42.mp4

This can also be reproduced in the [GeoImageDragging example]( http://openglobus.org/examples/geoImageDragging/geoImageDragging.html) when you make the dimensions smaller.

![image](https://user-images.githubusercontent.com/75586344/224081645-67aa1704-94b3-41e5-a995-f3316c8f8803.png)

It seems to be more noticeable the smaller the dimensions get. Changing the position of the corners during an event does not seem the cause. Having small initial dimensions also glitches the image.

**Comment by Zemledelec** [comment]
I think I know the reason. Texture clamping.

**Comment by Zemledelec** [comment]
Also, need to fix the precision issue, in the same way as Geometry does.

**Comment by Zemledelec** [comment]
@program-sam check the last master please.

**Comment by program-sam** [comment]
@Zemledelec looks absolutely perfect 👌
