### ISSUE TITLE
GeoImage transparency not handled as expected

### ISSUE THREAD

**Issue by program-sam** [openglobus/openglobus#659]
When adding GeoImages with transparency, such as this simple linear gradient, the result is not what you would expect

![Capture2](https://user-images.githubusercontent.com/75586344/226743454-6eccee6b-6738-4ae5-a579-ff495fcd7d65.PNG)

The alpha channel does not seem to get blended properly. Playing around lead me to the blend function defined in [Planet.js](https://github.com/openglobus/openglobus/blob/cea2436eb223fdf0cb0ba925af8abd430195e0e8/src/og/scene/Planet.js#L1229). Changing the blend function from `gl.blendFunc(gl.ONE, gl.ONE_MINUS_SRC_ALPHA);` to an alpha blend like `gl.blendFunc(gl.SRC_ALPHA, gl.ONE_MINUS_SRC_ALPHA)` seems to give a much more desirable result.

![Capture](https://user-images.githubusercontent.com/75586344/226744521-3da5ae47-99b2-4795-b999-115ee07c8f5d.PNG)

Would this be a desirable change? What was the reason for the original blend style?

**Comment by Zemledelec** [comment]
gl.SRC_ALPHA looks more convenient.
 @yeluoyunfei could you check please gl.blendFunc(gl.SRC_ALPHA, gl.ONE_MINUS_SRC_ALPHA) is ok for weather layers?
