### ISSUE TITLE
geoObjects textures not exporting / displaying correctly

### ISSUE THREAD

**Issue by program-sam** [openglobus/openglobus#663]
First of all, great job with the texturing of geoObjects and the blender export script! They are very convenient. But I seem to get a mismatch in what I export in Blender, and what shows up on the globe.

In blender the qube looks like this:

![Capture3](https://user-images.githubusercontent.com/75586344/227335427-b8da4bb4-665e-4e3e-b2cb-2995d576a6a0.PNG)

On the globe this comes out as 

![Capture4](https://user-images.githubusercontent.com/75586344/227335471-68de16ee-32cc-47b2-992d-4c38b3eb49a2.PNG)
![Capture5](https://user-images.githubusercontent.com/75586344/227335473-c6203631-fbdc-4ed3-9d90-f66a0b859c5b.PNG)

The output from the blender file is applied as follows:

```
let geoObjects = new EntityCollection({
  entities: [],
  scaleByDistance: [math.MAX32, math.MAX32, 1.0]
});

const model = {
	"indices": [
		1,2,0,3,6,2,7,4,6,5,0,4,6,0,2,3,5,7,1,3,2,3,7,6,7,5,4,5,1,0,6,4,0,3,1,5
	],
	"vertices": [
		-1.0,-1.0,0.0,-1.0,-1.0,2.0,-1.0,1.0,0.0,-1.0,1.0,2.0,1.0,-1.0,0.0,1.0,-1.0,2.0,1.0,1.0,0.0,1.0,1.0,2.0
	],
	"normals": [
		-0.5773491859436035,-0.5773491859436035,-0.5773491859436035,-0.5773491859436035,-0.5773491859436035,0.5773491859436035,-0.5773491859436035,0.5773491859436035,-0.5773491859436035,-0.5773491859436035,0.5773491859436035,0.5773491859436035,0.5773491859436035,-0.5773491859436035,-0.5773491859436035,0.5773491859436035,-0.5773491859436035,0.5773491859436035,0.5773491859436035,0.5773491859436035,-0.5773491859436035,0.5773491859436035,0.5773491859436035,0.5773491859436035
	],
	"texCoords": [
		0.24999994039535522,0.7472580075263977,0.2500000596046448,-0.0027420520782470703,0.75,0.4972580671310425,0.5000000596046448,-0.0027420520782470703,0.25,0.49725794792175293,0.25,0.2472580075263977,0.4999999701976776,0.4972580075263977,0.5,0.2472580075263977
	]
}

let obj3d = new Object3d({
  ...model,
  src: 'test.png',
});

let entity = new Entity({
lonlat: [4.40301, 51.211, 10],
name: 'box',
geoObject: {
    pitch: 0,
    yaw: 0,
    roll: 0,
    scale: 10,
    instanced: true,
    tag: 'plane',
    object3d: obj3d
}
});

geoObjects.addEntities([entity]);

geoObjects.addTo(globus.planet);
```

It seems that it does not correct for the fact that blender is a z-is-up world while webgl is a y-is-up world (or is this intentional?), and that something is still going wrong with the mapping of the texture onto to geoObject. Also the shading seems off compared to Blender / what I would expect.

I got the texture from [here](https://w7.pngwing.com/pngs/601/479/png-transparent-texture-mapping-centered-cube-number-centered-cube-number-three-dimensional-space-cube-texture-angle-3d-computer-graphics-thumbnail.png) If you want to replicate the setup.

**Comment by Zemledelec** [comment]
openglobus is [right-handed](https://en.wikipedia.org/wiki/Right-hand_rule#:~:text=Coordinates%20are%20usually%20right%2Dhanded,the%20second%20or%20y%2Daxis.) where **Y- UP**.

But, this looks like something is wrong with the texture coordinates. I'd recommend using tools from this issue https://github.com/openglobus/openglobus/issues/638 now. But, we need more information. @program-sam how did you get the coordinates?

@pavletto need assist:)

**Comment by program-sam** [comment]
Yes I noticed, but then most my remarks are on the [blender.py exporter script](https://github.com/openglobus/openglobus/blob/master/blender.py) that does not take into account that this is different from blender. Would it be desired that this script transforms the object so that what points up in blender ends up pointing up in openglobus? That belnder.py script is the code I used to extract indices, vertices, normals and textCoordinates. I did base myself on issue #638 which led me to use the that script.

**Comment by Zemledelec** [comment]
We will move to waveform .obj in https://github.com/openglobus/openglobus/issues/655

**Comment by program-sam** [comment]
that's great, so openglobus will natively be able to parse .obj files and the blender file will be deprecated? or would something like [wavefront-obj-parser](https://www.npmjs.com/package/wavefront-obj-parser) still be needed? I think #655 is a great choice

**Comment by Zemledelec** [comment]
Yes! It will be deprecated, as soon as we start to use simple waveforms...

FYI @pavletto

**Comment by program-sam** [comment]
Ah that is perfect!

**Comment by pavletto** [comment]
Hi @program-sam. Sorry for the long silence. You're right, the script was indeed broken - I didn't finish it.  It's now fixed on PR #674 . Could you please test it on your data? You can see the new texture example in `examples/geoObject`. Your cube example is there as well. Thanks for the tips and use of the script! I really appreciate it. obj support just around the corner)

**Comment by program-sam** [comment]
Would you look at that, that is perfect @pavletto! Thanks. A good script to use while waiting for the native .obj support 😄 

![image](https://user-images.githubusercontent.com/75586344/230985452-c5ba2ede-595b-42c3-aa2e-0e39e666275d.png)

**Comment by pavletto** [comment]
Hey @program-sam. Support of obj files is almost https://github.com/openglobus/openglobus/pull/677!
