### ISSUE TITLE
tileLayer opacity not showing geoObject behind it

### ISSUE THREAD

**Issue by program-sam** [openglobus/openglobus#664]
This might already be a very specific problem that is not that relevant many, but the situation is as follows:
I have a canvas tile layer that is offset by some amount. I would expect that objects that go behind or through this layer would still be visible in locations where the canvas tiles are transparent but that does not seem to be the case.

Object:
![Capture2](https://user-images.githubusercontent.com/75586344/227354184-c9be5317-e9a1-4b13-89a5-1ec7bb937ccf.PNG)

Object when offset layer is enabled
![Capture](https://user-images.githubusercontent.com/75586344/227354196-d457be57-f83a-458a-ae9c-2c5573861002.PNG)

Is this unavoidable given that these are two different ways of rendering things? Or is there a way to have the object not clip these tiles?

**Comment by Zemledelec** [comment]
Not sure that I understand correctly, nevertheless there is an option that could help somehow:` canvasLayer.setHeight(20) //move the layer 20 meters up,` And then, you can change the layer opacity the way you need it to be properly transparent according to the objects around.

**Comment by program-sam** [comment]
Excuse me if I couldn't make the example clearer. but I do indeed have a canvas layer with a height parameter so it 'floats' above the surface. But these tiles have transparancy. parts of the canvasses are completely transparent. And that works for other tiles layers. You can see the other tile layers behind the floating tiles. Yet, the entire canvas layer seems to cut of geoObjects at the set height. Even setting the opacity of the entire layer to 0.5 seems to cut of the geoObject and not show it passing through the layer.

here is a codepen to show the issue: [https://codepen.io/program-sam/pen/JjawbzN](https://codepen.io/program-sam/pen/JjawbzN)

![Capture8](https://user-images.githubusercontent.com/75586344/227467432-10c3d03d-6ba4-4c04-a71e-c151823551d1.PNG)

**Comment by Zemledelec** [comment]
There is a blending issue ahead. I've fixed it locally, but need to make some small but major changes in the engine.
![image](https://user-images.githubusercontent.com/5452251/227509775-6092f325-dc7c-40fb-94e6-c72ced2ba420.png)

**Comment by Zemledelec** [comment]
WIP: I've started a draft MR, Unfortunately, there is no proper way to make all objects blend correctly, for example, the cube is transparent, and you will be able to see the layer behind it. No. But opaque objects will be fine.

**Comment by Zemledelec** [comment]
MR https://github.com/openglobus/openglobus/pull/666

**Comment by program-sam** [comment]
Works as expected now, great work thanks!

**Comment by pavletto** [comment]
Hey  @program-sam. Support of obj files  is almost [ready](https://github.com/openglobus/openglobus/pull/677)!
