### ISSUE TITLE
Cannot set the opacity of a polyline

### ISSUE THREAD

**Issue by GuittonHubert** [openglobus/openglobus#669]
Hello @Zemledelec ,

I noticed an error calling setOpacity() in Polyline.js: `this.color.w` does not exist anymore.

To be able to set the opacity I get the private attribute `_defaultColor` modify the alpha channel value and finally call `setColorHTML()`. This is only a hack!

There are different ways of fixing this and I understand we must pay attention to assigning colors to the different parts of the polyline. Would it be possible to fix it, please? Thank you very much.

Have a nice day.

Hubert

**Comment by Zemledelec** [comment]
I'll check...

**Comment by Zemledelec** [comment]
Fixed
