### ISSUE TITLE
Proposition to improve the Timeline control

### ISSUE THREAD

**Issue by GuittonHubert** [openglobus/openglobus#670]
Hello @Zemledelec,

I propose the following to add a bit more flexibility:

- To add an option to the set current date and time of the TimelineControl instead of using the actual current date and time.
- To trigger the start of the time only when the play button of the TimelineView is clicked instead of starting as soon as this button is instantiated.

I have a piece of code available and would be pleased to submit it.

**Comment by Zemledelec** [comment]
Agree! Could you show PR please:)

**Comment by GuittonHubert** [comment]
Hello @Zemledelec 

Please find my proposal at https://github.com/GuittonHubert/openglobus.git on the PR-670 branch. I don't know how you want to proceed to review the code; I'm new to GitHub, so is a PR more suitable here?

Best regards,

Hubert

**Comment by pavletto** [comment]
Hi @GuittonHubert! Yes, it would be great to get pr

**Comment by Zemledelec** [comment]
For the rest `To add an option to the set current date and time of the TimelineControl instead of using the actual current date and time.` Let's create an issue with ui.
