### ISSUE TITLE
WMTS Grid 

### ISSUE THREAD

**Issue by GuittonHubert** [openglobus/openglobus#672]
Hello @Zemledelec 

I intend to write a layer using a WMTS grid with EPSG:4326. I studied the code for XYZ and canvas tiles layers so I think they will be the foundation of this code. However I'm blocked currently because I think that the current grid in use is XYZ and the geographical extent of a material.segment is aligned with the aforementioned grid. Could you please tell me if I'm wrong and possibly if there is a way to do it, if any? 

Thank you for your help.

Have a great day.

Hubert

**Comment by Zemledelec** [comment]
Yep! I know the guy who could help! @maxbebop we need your assistance:)

**Comment by maxbebop** [comment]
Hello @GuittonHuber.
If you want to use  EPSG:4326 and wgs84 try to use specify StrategyType  as quadTreeStrategyType.wgs84  in new instace of Globe. This strategy determines which quadtrees will be used. 
There are currently three implementations of the strategy:
- EarthQuadTreeStrategy  for Earth  and contains three quadtree
- MarsQuadTreeStrategy for Mars and contains two quadtree (wgs84)
- Wgs84QuadTreeStrategy - contains one quadtree
As an example, you can see the implementation for Mars: examples/mars/mars.html 

Hope this helps you.

**Comment by GuittonHubert** [comment]
Hello everyone,

Thank you for your answers; I will look at all that. 

Have a nice day,

Hubert

**Comment by Zemledelec** [comment]
We need a proper example for this...

**Comment by Zemledelec** [comment]
@GuittonHubert do you have a WMS or XYZ api for imagery tiles I could try with EPSG4326 projection? If not, it's ok, I'll publish it on my public Geoserver.

**Comment by GuittonHubert** [comment]
Hello @Zemledelec maybe you could try https://www.tefenua.gov.pf/api/wmts with layer CarteSHOM. Please find a snapshot with QGIS
![Screenshot 2023-04-18 at 15 34 26](https://user-images.githubusercontent.com/61505725/232793959-497d7566-f1ba-49df-b1c2-be735c749b79.png)

Information:
Extent: -178.7274413804020980,-34.2514241806426440 / -117.9489166381400622,0.1772407522678508
Tile size: 256x256 pixels

I hope this can help you.

**Comment by Zemledelec** [comment]
Hi @GuittonHubert, could you help with this, where do I go wrong? [https://www.tefenua.gov.pf/api/wmts?layer=TEFENUA:CarteSHOM&style=s&tilematrixset=EPSG:4326&Service=WMTS&Request=GetTile&Version=1.0.0&Format=image/png&TileMatrix=EPSG:4326:5&TileCol=1&TileRow=15](https://www.tefenua.gov.pf/api/wmts?layer=TEFENUA:CarteSHOM&style=s&tilematrixset=EPSG:4326&Service=WMTS&Request=GetTile&Version=1.0.0&Format=image/png&TileMatrix=EPSG:4326:5&TileCol=1&TileRow=15)

**Comment by GuittonHubert** [comment]
Hello @Zemledelec,

I think the trouble is the image format, it appears to be image/png8 on this server. Dunno if it is common, sorry... Please find hereafter, a working request and the result below:


https://www.tefenua.gov.pf/api/wmts?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=TEFENUA:CarteSHOM&STYLE=&FORMAT=image/png8&TILEMATRIXSET=EPSG:4326&TILEMATRIX=EPSG:4326:6&TILEROW=36&TILECOL=8

<img width="258" alt="image" src="https://user-images.githubusercontent.com/61505725/233836313-9f1aa705-d47b-40f6-9b0a-f1cb21075b5a.png">


Query Parameters:

|  Keys               | Your Values                     | Mine                               |
|---------------|------------------------|------------------------|
|  layer               | TEFENUA:CartesSHOM | TEFENUA:CarteSHOM |
| style                | s                                       |     (empty)                     | 
| tilematrixset   | EPSG:4326                     | EPSG:4326                    | 
| Service           | WMTS                              | WMTS                            |
| Request          | GetTile                             |  GetTile                          |
| Version           | 1.0.0                                  | 1.0.0                               |   
| Format            | image/png                        | image/png**8**           | 
| TileMatrix       |  EPSG:4326:5                  | EPSG:4326:6               |
| TileCol            | 1                                        | 8                                    |
| TileTow          |  15                                     |  36                                  | 


**Note:** In [07-057r7_Web_Map_Tile_Service_Standard ](https://portal.ogc.org/files/?artifact_id=35326)/ Table 29 — GetTile operation request URL parameters: All parameter names are here listed using mostly lower case letters. However, **any parameter name capitalization SHALL be allowed in KVP encoding**, see subclause 11.5.2 of OWS Common [[OGC 06-121r3](https://portal.ogc.org/files/?artifact_id=20040)].

**Comment by Zemledelec** [comment]
Thank you @GuittonHubert for the helpful description! Could you please check this pull request new sandbox epsg4326 folder inside? https://github.com/openglobus/openglobus/pull/684
If it's ok, we need to add a convenient name for this projection strategy template.
FYI @maxbebop @pavletto 

P.S.
...and WMTS Layer class with WMTS options.

**Comment by Zemledelec** [comment]
...and WMTS Layer class with WMTS options
