### ISSUE TITLE
Completing the RenderEvents / KeyboardHandler removeEvent function

### ISSUE THREAD

**Issue by program-sam** [openglobus/openglobus#681]
I was thinking about completing the removeEvent function in the KeyboardHandler since I might have a use for that functionality.
https://github.com/openglobus/openglobus/blob/31e3861751e3c8d4e69198f107570e8bb7a7ca19/src/og/input/KeyboardHandler.js#L35-L39

The way it should be done seems straight forward, just removing the `{ callback: callback, sender: sender, priority: priority }` from the CallbackArray and it shouldn't be called anymore. I believe the reason why it wasn't completed yet is because of the question, how do you target the event you want to remove? Since there can be multiple events for one keyCode, it is also not enouth to have the event type and the keyCode when removing an event. perhaps working with names is the way to go? Similar as how layers have names. Then you can easily remove an event based on the event type and the event name.

I'd gladly make the suggested changes, but wanted to check with you guys before diving in.

**Comment by Zemledelec** [comment]
...let's take a look...ok...I just have checked `MouseHandler `and `KeyboardHandler`, and I want to say that there is some inconsistency in interface design, for instance, both modules have `setEvent `and `addEvent `methods which make the same procedure setting (adding) some event handler...ok...but in the class `RendererEvent `(which is _"facade"_ for events), it called on in here, and its superclass...but `setEvent `and `addEvent `are using in different context thou...might be it's ok...but, if we decide to rename them for example `on(..)` fine.
About `removeEvent`, agree, that it is an important method if you want the keyboard handling configurable. It looks pretty straightforward, so while I fix **GeoImage.src**, @program-sam is welcome to apply this function::))

In the future, we could add even some control (plugin) for configuring every common behavior, the same as game configs do.

**Comment by program-sam** [comment]
Alright! I'd be happy to give it a shot. I must say I got confused that it was named 'on' and 'off' in RenderEvent. Is it an idea to just go for the naming add / remove everywhere? or does on/off and set have some significance / difference in meaning?

I'll have a go at refactoring the inconsistencies a bit, and applying the removeEvent. For that I will also add a 'name' to events, so you can remove events by name. I'll be around if I have questions 😉.

**Comment by program-sam** [comment]
Suggested changes in #705 , Let me know what you think

**Comment by Zemledelec** [comment]
@program-sam check please https://github.com/openglobus/openglobus/pull/753

**Comment by Zemledelec** [comment]
I wasn't sure that the task is quite obvious and comparatively easy to make it as easy as possible. I'd like you to take a look at how I fixed the method, it looks like the `addEvent` now, it has `stamp` method the same as the initial `Event `class, and there are a few tests, but the main test of course is working in your controls.

**Comment by samvanemelen** [comment]
yes that is perfect! the `openglobus_id` stamp and the `keyboardHandler.getPressedKeysCallbacks()` are exactly what I needed to be able to manipulate the existing key events, thanks 🙏🏼

**Comment by program-sam** [comment]
yes that is perfect! the openglobus_id stamp and the keyboardHandler.getPressedKeysCallbacks() are exactly what I needed to be able to manipulate the existing key events, thanks 🙏🏼
