### ISSUE TITLE
Sample websites and API documents cannot be inserted, 404

### ISSUE THREAD

**Issue by lisentowind** [openglobus/openglobus#683]
Sample websites and API documents cannot be inserted, 404

**Comment by Zemledelec** [comment]
API, examples are temporarily unavailable. It's "under construction".

**Comment by lisentowind** [comment]
> API, examples are temporarily unavailable. It's "under construction".

Okay, thank you. I'll just look at the source code example

**Comment by lisentowind** [comment]
> API，示例暂时不可用。它正在“建设中”。

Hello, I am currently experiencing an issue with not being able to display Chinese characters, but I have introduced my custom font. How can I specify using my font in the label properties? I have tried using fontIndex and fontAtlas to specify my own font, but it still cannot be rendered
![image](https://user-images.githubusercontent.com/88653280/234216936-0503fef2-3122-41ca-9537-72af3dd02237.png)

![image](https://user-images.githubusercontent.com/88653280/234216076-d173858e-07a5-4d86-8901-de80b125d6d3.png)

![image](https://user-images.githubusercontent.com/88653280/234217137-b5d97b11-237c-455e-a67c-226b61a2a7be.png)

**Comment by pavletto** [comment]
@Tingfenghhh glad to see you at openglobus. We are currently trying to improve our site and the process of uploading it. As a stopgap measure, I have made the documentation available on the [github pages](https://openglobus.github.io/openglobus/).
Are you setting `face` property in the [label](https://openglobus.github.io/openglobus/module-og_entity_Label-Label.html) instance?

**Comment by lisentowind** [comment]
> @Tingfenghhh glad to see you at openglobus. We are currently trying to improve our site and the process of uploading it. As a stopgap measure, I have made the documentation available on the [github pages](https://openglobus.github.io/openglobus/). Are you setting `face` property in the [label](https://openglobus.github.io/openglobus/module-og_entity_Label-Label.html) instance?

I can now display my custom font, but it seems that it cannot be rendered correctly. The recommended msdf bmfont xml used does not seem to convert the font correctly

**Comment by pavletto** [comment]
Please describe in more detail how you generate the atlas. describe the commands and attach a font if possible. Is this iransans this rtl font correct?

**Comment by lisentowind** [comment]
> Please describe in more detail how you generate the atlas. describe the commands and attach a font if possible. Is this iransans this rtl font correct?

Thank you for your help. We can now render the normal font, but the basic character set of Chinese characters is over 3500, which cannot be fully rendered onto a single image. We can only render a small amount of our own custom text haha

**Comment by Zemledelec** [comment]
Hey @Tingfenghhh you can enlarge the font atlas image size to 4096 is the maximal texture size for WebGL. Check ./fonts/run.cmd, there is a few parameters you could play with...I see 1024 is the size of texture, and 32 is the character size, so say you have 3050 characters, the matrix size sqrt(3050) = 56. 1024 / 56 = 18, too small I guess, 33 * 56  = 1848 - the size of the atlas you need. Try to set 2048x2048:) Cheers! Don't forget to fill charset.txt with, it could be a nice test for texture atlas! Cheers!

**Comment by lisentowind** [comment]
> Hey @Tingfenghhh you can enlarge the font atlas image size to 4096 is the maximal texture size for WebGL. Check ./fonts/run.cmd, there is a few parameters you could play with...I see 1024 is the size of texture, and 32 is the character size, so say you have 3050 characters, the matrix size sqrt(3050) = 56. 1024 / 56 = 18, too small I guess, 33 * 56 = 1848 - the size of the atlas you need. Try to set 2048x2048:) Cheers! Don't forget to fill charset.txt with, it could be a nice test for texture atlas! Cheers!

Thank you for replying to my question. I have tried to change the size of the image, but the msdf bmfont xml tool converted Chinese characters and rendered them garbled. Then I tried this online conversion tool, msdf bmfont web, which can render the font I want normally (● '◡' ●). Happy

**Comment by Zemledelec** [comment]
Let's close the issue, btw we are going to fix documentation in terms of new homepage task.
