### ISSUE TITLE
Attach/detach the globe to/from an HTMLElement

### ISSUE THREAD

**Issue by GuittonHubert** [openglobus/openglobus#691]
Hello all,

In my application a globe instance is created with a reference to a HTMLDivElement. During the life cycle of this application:
- The element is removed from the DOM by the user, while the globe instance still exists.
- Later on a new HTMLDivElement is created with the same element id.

My intention is to keep using the current globe instance and attach it to the new element. This fails of course since the div attribute of the globe instance cannot be updated. 

Is there a way to proceed and if not how can I delete the globe instance and recreate a new one (setting the variable pointing to the globe instance to null does not work)? Thank you for your answers.

Best regards,

Hubert.

--
Some comments from @wizzed from https://github.com/openglobus/openglobus/issues/310

> I have an issue where 4 dedicated workers are created every time a map is created. Are there any methods to clear up the workers or to clean up the map?

> I would like to clear all references and clear all memory usage, some sort of globe.clearAll(), or globe.delete() which clears everything and free up the memory.

> Yes, everything, I'm using reactjs and it kinda eats up memory everytime I navigate back and from the map page. So I'm kinda looking for a way to clean up the map efficiently...

**Comment by Zemledelec** [comment]
Good question! A few times ago I was asked almost the same question here https://github.com/openglobus/openglobus/issues/310

I'm going to implement new examples on the homepage, and in the new version, it will be considered.

**Comment by GuittonHubert** [comment]
Well spotted! Indeed I'm mostly in the same situation as the one mentioned in #310

**Comment by GuittonHubert** [comment]
Please do you have a draft piece of code to provide me with, or could you give me some details? This way, I may think about a solution. Thank you very much.

**Comment by Zemledelec** [comment]
I liked your `detach` method. Firstly, It might be it's not a "detach" because it means that you could attach it again, but in this case, all resources must be kept safely. Secondly, the main idea in the issue is about some destructor(dispose, remove, delete, etc) method. But It's fine.

**Comment by Zemledelec** [comment]
WIP
