### ISSUE TITLE
geoImage setSrc() not working

### ISSUE THREAD

**Issue by program-sam** [openglobus/openglobus#694]
The geoImage has a function to change the source of the texture:

https://github.com/openglobus/openglobus/blob/3775233c77b5304c64ca1faed26945cec55413b0/src/og/layer/GeoImage.js#L47

But this does not seem to function as expected. I would expect the geoImage layer to update with the new Image url as source?

I have made a codePen showing the issue:

https://codepen.io/program-sam/pen/QWZMZmO

**Comment by Zemledelec** [comment]
Ohh, thanks! I'll fix!

**Comment by Zemledelec** [comment]
PR https://github.com/openglobus/openglobus/pull/697

@program-sam could you check, please:)

**Comment by program-sam** [comment]
Awesome, seems to work fine!

https://user-images.githubusercontent.com/75586344/236323104-49d5cb32-51a3-4094-91d5-a2c4680ed992.mp4

Although there does seem to be an occasional glitch in the texture, similar to the texture clamping issue in #646 (not the image sizes or image warping, that's my code). But only when the image just changed and not all the time, after moving it for example it seems fine. So I wouldn't be able to guess why that is.

**Comment by Zemledelec** [comment]
I strongly recommend do not use GeoImage for the objects! Instead use GeoObject, as a plane with a texture! 

Why? GeoImage unfortunately uses one layer instance and the layers after 10 or 20 (I didn't count) it getting worked slower. Actually, I use GeoImages for a few objects on a map. In your case, it seems to be that there will be a lot of objects like this! And GeoObjects could have more interesting functionalities like rotating and changing positions on the fly etc.

Btw, the clamping texture is still here... one-pixel size transparent border in the image could help.

**Comment by Zemledelec** [comment]
P.S. @program-sam you make awesome things! I never thought it could be used like that! Please make proposals, and prioritize them, I could help with this. Thank you!

**Comment by program-sam** [comment]
> I strongly recommend do not use GeoImage for the objects! Instead use GeoObject, as a plane with a texture!
> 
> Why? GeoImage unfortunately uses one layer instance and the layers after 10 or 20 (I didn't count) it getting worked slower. Actually, I use GeoImages for a few objects on a map. In your case, it seems to be that there will be a lot of objects like this! And GeoObjects could have more interesting functionalities like rotating and changing positions on the fly etc.
> 
> Btw, the clamping texture is still here... one-pixel size transparent border in the image could help.

No I don't use them for all objects. There is only one GeoObject and that gets reused every time you place an object. When buildings are placed, I show them using a canvas tileLayer as discussed in #613 😉

I thought about using GeoObjects for all objects, but I wasn't sure about performance yet. Also 3d modeling takes a lot more time than 2d assets so that's why it's in CanvasLayers now.

I figured the difference in performance between GeoObjects & GeoImages might be negligible if it is just for one image that gets reused? Or are there still differences?

> P.S. @program-sam you make awesome things! I never thought it could be used like that! Please make proposals, and prioritize them, I could help with this. Thank you!

Thanks man! I love to hear that! I had this idea for a while and openglobus, an opensource library for showing a 3d globe, was what I had been looking for all this time. And that in JS, the language I use the most! ❤️

I'd be happy if I can help in some places to return the favor.
