### ISSUE TITLE
Drawing new features on the globe

### ISSUE THREAD

**Issue by program-sam** [openglobus/openglobus#706]
I think that being able to draw shapes (polygons, polylines etc.) is an essential feature for any online mapping library. Has this feature come up already? If I have time I could see how this could work, by taking inspiration from [the openlayers implementation](https://github.com/openlayers/openlayers/blob/main/src/ol/interaction/Draw.js) for example. That won't be soon but I wanted to share the idea already.

**Comment by Zemledelec** [comment]
I'll start...https://github.com/openglobus/openglobus/pull/714
