### ISSUE TITLE
Polyline with multiple colors

### ISSUE THREAD

**Issue by GuittonHubert** [openglobus/openglobus#723]
Hello All,

I am trying to draw a polyline with pathLonLat set as an array of LonLat objects and pathColors as an array of Vec4. The structure is as follows:

```
pathLonLat: [[LonLat1, LonLat2, LonLat3, LonLat4], [LonLat5, LonLat6, LonLat7], [LonLat8, LonLat9, LonLat10, LonLat11]]
pathColors: [[Vec41, Vec41, Vec41, Vec41], [Vec42, Vec42, Vec42], [Vec43, Vec43, Vec43, Vec43]]
```
Example color:
- Vec4 {x: 0.24313725490196078, y: 0.2627450980392157, z: 0.9725490196078431, w: 1}

I expect to have a polyline with three "sections" of different colors (Vec41, Vec42, Vec43). However, the polyline is drawn but with "holes":
![image](https://github.com/openglobus/openglobus/assets/61505725/a5782ef3-06dc-40e3-ac36-943a7355a940)

I even tried without any success:
- with different browsers (macOS-M1 chip) Firefox, Safari, Chrome
- using a different structure for the pathColors:

`pathColors: [Vec41, Vec42, Vec43]
`

Could you please tell me what is wrong? Thank you for your support.

Hubert

**Comment by Zemledelec** [comment]
Hi @GuittonHubert , Try array instead of Vec4 as a color, like [r, g, b, a]. Looks like vec4 is not supported in pathColors.

**Comment by GuittonHubert** [comment]
Hi @Zemledelec,

Thank you for your answer. The color is taken into account when switching from og.Vec4 to array as you said. Perfect!

Regarding holes however; the "issue" is not an issue in fact. I realized that it is required to repeat some coordinates in pathLonLat to ensure there is a continuity between the segments; that is to say:


`pathLonLat: [[LonLat1, LonLat2, LonLat3, LonLat4], [LonLat4 , LonLat5, LonLat6, LonLat7], [LonLat7, LonLat8, LonLat9, LonLat10, LonLat11]]`

That's logical...

As a side note, the following structure seems to be sufficient:

`pathColors: [Vec41, Vec42, Vec43]
`

**Comment by GuittonHubert** [comment]
It's working, so I close this issue. Thank you for your help.

**Comment by Zemledelec** [comment]
Thanks! FYI @GuittonHubert  Just in case, long polylines could have some sort of z-fighting artifacts, just need more points between them.
