### ISSUE TITLE
ScaleControl Initialization Failure

### ISSUE THREAD

**Issue by GuittonHubert** [openglobus/openglobus#724]
Hello,

I have this error in rev e9e2b6670836f1823947c80f33200c9d7ccdbb74

`TypeError: undefined is not an object (evaluating 'this.planet.terrain.events.on')`

In src/og/control/ScaleControl.js (line 58-60): terrain is not initialized. This can be tested with examples/emptyTerrain

Could you confirm this issue please? As a workaround I commented the aforementioned section.

Hubert

**Comment by Zemledelec** [comment]
check
