### ISSUE TITLE
Layer blending and flickering

### ISSUE THREAD

**Issue by program-sam** [openglobus/openglobus#732]
A recent change seems to have altered the way layers with an alpha channel are blend. The change seems to have occurred somewhere in the changes of 15.5 -> 16.0. Reverting back to 15.5 fixes the issue but I have not yet been able to isolate the exact code change that causes it.

Layers used to be blend like this in in 15.5 as changed in #659 :

https://github.com/openglobus/openglobus/assets/75586344/37967207-a7f1-49a7-9fb4-9eae54a66ba2

While they now look like this since 16.0, and flicker on, what seems to be, each draw event.

https://github.com/openglobus/openglobus/assets/75586344/f4be59fd-7b3c-4984-8b65-5afa4de2ae15

I have made a codepen example: https://codepen.io/program-sam/pen/dyQPEBr
In the codepen the layer does not flicker every draw event it seems, but it shows the same flicker when the window is resized and the layer should be all white, but there seems to be some black in the transparent regions. In the codepen you can switch from the latest to using 15.5 by changing the og src from `www.openglobus.org/og.umd.js` to `https://bitbucket.org/!api/2.0/snippets/programsamog/Gzed6X/6b1fe74ea7e5109fe12ae9df9f2f781bf21e1ee5/files/snippet.txt`

I checked if #700 had anything to do with it, but reverting those changes had no effect.

Any ideas?

**Comment by Zemledelec** [comment]
I know the reason...it happens when the mouse is moving. Of course it's not the mouse fault:)

**Comment by Zemledelec** [comment]
Could you check please @program-sam https://github.com/openglobus/openglobus/pull/735

**Comment by Zemledelec** [comment]
Thank you for the example @program-sam! Check the MR, I'll clean it up...and need to think about how to manage blending manually...

MR https://github.com/openglobus/openglobus/pull/735

**Comment by program-sam** [comment]
Perfect, using the default blend seems to work perfectly. Out of curiosity, what is the use case for the enableBlendOneSrcAlpha?

**Comment by Zemledelec** [comment]
enableBlendOneSrcAlpha blends planet segments. but another one blends 3d objects and labels better. I can't say this is the correct way and never would change. enableBlendOneSrcAlpha - is basic blending that works fine, and frankly speaking, should be default blending, but right now the default is different, and I can't say that this is a good decision, but it works.
