### ISSUE TITLE
deactivate sun

### ISSUE THREAD

**Issue by maxargy** [openglobus/openglobus#759]
hello there
from v0.17.x seem that the option
var globus = new Globe({
    ...
    "sun": {"active": false}
});
doesn't work anymore, while
globus.sun.deactivate();
works

Best regards,
Massimiliano

**Comment by Zemledelec** [comment]
Hi! Thanks for the bug report! It's true because the initialization sequence was changed because of deferred planet initialization refactoring. I'll fix it in the typescript migration branch.

**Comment by Zemledelec** [comment]
It's fixed in https://github.com/openglobus/openglobus/pull/756
