### ISSUE TITLE
Polyline wrong render if near ground

### ISSUE THREAD

**Issue by anhaabaete** [openglobus/openglobus#799]
When vectors draws render near the ground a problem happen
[Gravação de tela de 2023-12-11 00-50-25.webm](https://github.com/openglobus/openglobus/assets/32251249/66584760-a9e4-470f-97ab-7e5088d54fd6)
[Gravação de tela de 2023-12-11 00-49-40.webm](https://github.com/openglobus/openglobus/assets/32251249/52d78596-4508-4c2d-a9ab-4dd8b2f7c271)

**Comment by Zemledelec** [comment]
Hi @anhaabaete ! This is because Polylines are kind of 3D objects which collides with the ground mesh. Try this in the example:

```
        const pointLayer = new Vector("points", {
            'relativeToGround': true,
            'visibility': true,
            'polygonOffsetUnits': -1000 // offset to camera in meters
        });
```

or

add altitude value to a polyline entity like this:

`clampToGround `change to `relativeToGround`

```
        const pointLayer = new Vector("points", {
            'relativeToGround': true,
            'visibility': true
        });
```

```
        const polylineEntity = new Entity({
            'polyline': {
                'pathLonLat': pathLonLat,
                'pathColors': pathColors,
                'thickness': 3.3,
                'isClosed': true,
                altitude: 10 // meters above the ground
            }
        });
```

If you need more geometries, I suggest to use Geometry entity LineString WKT the same as https://sandbox.openglobus.org/examples/vectorLayer

**Comment by anhaabaete** [comment]
'polygonOffsetUnits': -1000 was a good option and resolved here

**Comment by Zemledelec** [comment]
> 'polygonOffsetUnits': -1000 was a good option and resolved here

Be careful, it "moves"(view look) polyline towards to the camera. It means that if your camera is closer than 1000 meter, the object becomes behind the camera and invisible in the current camera view. It means that `polygonOffsetUnits ` works on a distance.
