### ISSUE TITLE
setGeometry on Entity gives error: this.geometry.setVisibility is not a function

### ISSUE THREAD

**Issue by program-sam** [openglobus/openglobus#802]
Hi! I've stumbled upon this unexpected behavior and I'm not sure if it's a bug, or whether I'm missing something when trying to change the geometry of an existing Entity. I do remember it working in https://github.com/openglobus/openglobus/issues/645 So it feels like something changed after that.

here is a snippet of the issue.

https://codepen.io/program-sam/pen/ExMdOvb

i would expect the setGeometry to accept similar inputs as to what it takes to create the entity, but that does not seem to be the case. I have not tested all Entity options, but it seems also to be the case for Polylines

**Comment by Zemledelec** [comment]
Try:

```
entity.geometry.setGeometry({
        "type": "Polygon",
        "coordinates": [[
            [ 4, 0 ],
            [ 1, 1 ],
            [ 1, 3 ],
            [ 3, 3 ],
            [ 3, 1 ]
          ]]
    })
```

Meanwhile I'll check entity.setGeometry

**Comment by Zemledelec** [comment]
This is a bug, a lack of consistency in the constructors, I'll fix it in a moment...

**Comment by Zemledelec** [comment]
@program-sam, check it up, please! I've fixed it, but, you have to use `new Geometry({...})` like this:

```
if (true){
    entity.setGeometry(new Geometry({
        "type": "Polygon",
        "coordinates": [[
            [ 3, 1 ],
            [ 1, 1 ],
            [ 1, 3 ],
            [ 3, 3 ],
            [ 3, 1 ]
        ]]
    }));
}
```

If you need it as a json, please, create another issue.

**Comment by program-sam** [comment]
Allright thanks! Although https://github.com/openglobus/openglobus/issues/802#issuecomment-1938114639 is a functional workaround, https://github.com/openglobus/openglobus/issues/802#issuecomment-1938144126 seems a lot more as expected, thanks!
