### ISSUE TITLE
Do you have plans to support MVT？

### ISSUE THREAD

**Issue by xrui94** [openglobus/openglobus#817]
Do you have plans to support Mapbox vector tiles（MVT）？

**Comment by Zemledelec** [comment]
Hey @xrui94 ! I dream about it, but 3DTiles first! 
Cheers!

**Comment by xrui94** [comment]
> Hey @xrui94 ! I dream about it, but 3DTiles first! Cheers!

Hi @Zemledelec! Thank you for your reply. Recently, I am researching the rendering of MVT data by webgl. 
Although cesium engine is here in my daily work,  I don't really like something of its designs. I have a understanding of the 3DTiles (v1.0.0) format, and if possible, I would be happy to write some code for the openglobus project.

**Comment by Zemledelec** [comment]
I'd love write the implementation of 3dtiles too! Would be very appreciated for the archuitecture. For instance We could discuss the architecture, and try to implement some parts of the 3dtiles. Point cloud, Google photorealistic 3dtiles, gltf, visualizing debugging infrmation on the map, such as quad nodes, etc.

**Comment by xrui94** [comment]
> I'd love write the implementation of 3dtiles too! Would be very appreciated for the archuitecture. For instance We could discuss the architecture, and try to implement some parts of the 3dtiles. Point cloud, Google photorealistic 3dtiles, gltf, visualizing debugging infrmation on the map, such as quad nodes, etc.

Okay, when I have free time, I will submit some PRs.
