### ISSUE TITLE
Unable to select an entity on a vector layer with touch events.

### ISSUE THREAD

**Issue by KoschKX** [openglobus/openglobus#830]
I have a vector layer and I want to be able to select the objects. It works with mouseenter events, but with touch I am getting the following webGL warnings. 

WebGL: INVALID_ENUM : readPixels: invalid type
[.WebGL-0x13000e34600] GL_INVALID_OPERATION: Missing read attachment.

The pickingObject turns up null. I was able to get it to select the objects by changing the renderEvents.ts file at around line 720, adding "||(this._oneTouchStart)" to the condition and then commenting out the framebuffer code that was causing the warnings in handleTouchEvents() at around line 956.

I'm not familiar with the code yet, so I'm not sure what that code is supposed to be doing. Maybe I'm just doing something wrong, but the problem also happens in the example. Hope this helps.

**Comment by Zemledelec** [comment]
I've made a commit to the master. Check it out, please.

I almost forgot about touch devices. Need to do more tests, not sure if this will fix all events.

**RendererEvents.ts: 971**

```
protected handleTouchEvents() {
        let _this = this as RendererEventsHandler;

        let ts = this.touchState;

        let tpo = ts.pickingObject,
            tpe = null;

        if (ts.touchCancel) {
            this.dispatch(_this.touchcancel, ts);
            ts.touchCancel = false;
        }

        if (ts.touchStart) {
            let r = this.renderer;

            r.readPickingColor(ts.nx, 1 - ts.ny, _currPickingColor);

            // r.pickingFramebuffer!.activate();
            // r.pickingFramebuffer!.readPixels(_currPickingColor, ts.nx, 1.0 - ts.ny, 1);
            // r.pickingFramebuffer!.deactivate();

            let co = r.getPickingObjectArr<any>(_currPickingColor);
```

P.S.
BTW readPixel is asynchronous here, so it might be more interesting if you get inside the engine.

**Comment by KoschKX** [comment]
Seems to work for me . Thanks :D
