### ISSUE TITLE
Earth3 host certificate has expired

### ISSUE THREAD

**Issue by waldenn** [openglobus/openglobus#85]
See: https://earth3.openglobus.org/10/376/526.ddm

"Issued On	Friday, November 10, 2017 at 8:05:00 AM
Expires On	Sunday, December 10, 2017 at 8:05:00 AM"

Maybe use the https://letsencrypt.org ACME script for managing these certificates?
I've found their ACME script easy to use (for Apache2).

**Comment by waldenn** [comment]
From where can this whole DDM dataset be downloaded?

**Comment by Zemledelec** [comment]
ddm is a mercator grid tile set with 33x33(SRTM ~3 arc sec) of floats grid for elevation data. ddms are available via http://earth3.openglobus.org/{zoom}/{y}/{x}.ddm check it how it works out here ./terrain/GlobusTerrain.js
ddm was made from here http://viewfinderpanoramas.org/ - > http://viewfinderpanoramas.org/Coverage%20map%20viewfinderpanoramas_org3.htm with some of my handytool from https://github.com/openglobus/tools/tree/master/HeightsAdapter (don't see here, it is useless without a faq)

Thanks for letsencrypt.org i'll try...

**Comment by waldenn** [comment]
Ok, thanks for the info.

**Comment by Zemledelec** [comment]
Thank, walden! I've done it at last!
