### ISSUE TITLE
Better mobile support

### ISSUE THREAD

**Issue by waldenn** [openglobus/openglobus#88]
I've got an iPad2 with the older iOS9 Safari and OpenGlobus does not work there (black screen on the examples). Maybe the newer iOS Safari does work with the examples?

My windows mobile phone also does not seem to work, though it does support various WebGL / canvas stuff. I don't have an Android phone, but does that work?

Not sure what the issues are (I'm on Linux, so I can't do remote USB debugging). I tried using https://github.com/remy/jsconsole to see where the issues are, but the tool is not working for me currently.

I think it would be interesting to see what the issues are and if they are worth fixing.

**Comment by Zemledelec** [comment]
I have an android 6 and it works well, 
it had worked on ipad air 2 before es6, but it doesn't work right now. But WebGL is ok, I suppose that is something wrong with es6 on safari.
